# Depressive and Suicidal text classification

**Datasets used:**
1. [Classified Twitter posts](https://www.kaggle.com/datasets/munkialbright/classified-tweets)
2. [Derived dataset from Murarka et al., Nikhileswar Komati and Suchintika Sarkar](https://www.kaggle.com/datasets/priyangshumukherjee/mental-health-text-classification-dataset)

## Imports

In [1]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import random

## Download the dataset

In [2]:
import kagglehub

In [3]:
path1 = kagglehub.dataset_download("munkialbright/classified-tweets")
print("Path to dataset 1:", path1)

Using Colab cache for faster access to the 'classified-tweets' dataset.
Path to dataset 1: /kaggle/input/classified-tweets

In [4]:
path2 = kagglehub.dataset_download("priyangshumukherjee/mental-health-text-classification-dataset")
print("Path to dataset 2:", path2)

Using Colab cache for faster access to the 'mental-health-text-classification-dataset' dataset.
Path to dataset 2: /kaggle/input/mental-health-text-classification-dataset

## Seed the randoms

In [5]:
SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)
random.seed(SEED)

## Set up dataframes

In [6]:
# We do multi-label (binary label) classification
# with possible missing values in the labels
# 0 = not present, 1 = present, -1 = unknown/missing
# normal text have all labels = 0

df_all = pd.DataFrame(columns=["text", "isSuspicious", "isRacist", "isSexist", "isHate", "isDepressive", "isSuicidal", "isAnxiety"])

In [7]:
df_all1 = pd.read_csv(path1 + "/classified_tweets.csv")
# print columns
print("Columns in dataset 1:", df_all1.columns)

# cols =
# 'text' -> text of the tweet
# 'suspicious' -> 0 or 1 if the tweet is suspicious (contains harmful content)
# 'cyberbullying' -> 0 if nothing, 1 if racist, 2 if sexist
# 'hate' -> 0 or 1 if the tweet contains hate speech
# 'suicidal' -> 0 or 1 if the tweet contains suicidal content

# this dataset has no depressive / anxiety labels, so we will fill them with -1 (unknown/missing)
df_all1["isDepressive"] = -1
df_all1["isAnxiety"] = -1
# rename columns to match our format
df_all1.rename(columns={
    "suspicious": "isSuspicious",
    "hate": "isHate",
    "suicidal": "isSuicidal"
}, inplace=True)

# convert cyberbullying to isRacist and isSexist
df_all1["isRacist"] = df_all1["cyberbullying"].apply(lambda x: 1 if x == 1 else 0)
df_all1["isSexist"] = df_all1["cyberbullying"].apply(lambda x: 1 if x == 2 else 0)
# drop the original cyberbullying column
df_all1.drop(columns=["cyberbullying"], inplace=True)

display(df_all1.head())

df_all = pd.concat([df_all, df_all1], ignore_index=True)

Columns in dataset 1: Index(['text', 'suspicious', 'cyberbullying', 'hate', 'suicidal'], dtype='object')

,text,isSuspicious,isHate,isSuicidal,isDepressive,isAnxiety,isRacist,isSexist
0,Uhmm like 6th grade on a corner of a street....,0,0,0,-1,-1,0,0
1,a) JTP is a douchebag b) Stewart kicks ass!,1,0,0,-1,-1,0,0
2,ditto bitch!,1,0,0,-1,-1,0,0
3,damn I have to drive my dad to the airport tha...,0,0,0,-1,-1,0,0
4,:],0,0,0,-1,-1,0,0

In [8]:
df_all2 = pd.read_csv(path2 + "/mental_heath_unbanlanced.csv")

# print columns
print("Columns in dataset 2:", df_all2.columns)

# cols =
# 'text' -> text of the post
# 'status' -> the text Normal, Depression, Suicidal, Anxiety

def getRow(
        default_num : int,
        change_key : str = None,
        change_value : int = None
    ):
    res = {
        "isSuspicious": default_num,
        "isRacist": default_num,
        "isSexist": default_num,
        "isHate": default_num,
        "isDepressive": default_num,
        "isSuicidal": default_num,
        "isAnxiety": default_num,
    }
    if change_key is not None and change_value is not None:
        res[change_key] = change_value
    return res

mapping_cols = {
    "Normal"     : getRow(0),
    "Depression" : getRow(-1, "isDepressive", 1),
    "Suicidal"   : getRow(-1, "isSuicidal", 1),
    "Anxiety"    : getRow(-1, "isAnxiety", 1),
}

# apply the mapping to the status column and create new columns
for status, mapping in mapping_cols.items():
    df_all2.loc[df_all2["status"] == status, ["isSuspicious", "isRacist", "isSexist", "isHate", "isDepressive", "isSuicidal", "isAnxiety"]] = mapping.values()

# drop the original status column
df_all2.drop(columns=["status", "Unique_ID"], inplace=True)

display(df_all2.head())

df_all = pd.concat([df_all, df_all2], ignore_index=True)

Columns in dataset 2: Index(['Unique_ID', 'text', 'status'], dtype='object')

,text,isSuspicious,isRacist,isSexist,isHate,isDepressive,isSuicidal,isAnxiety
0,oh my gosh,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0
1,"trouble sleeping, confused mind, restless hear...",-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0
2,"All wrong, back off dear, forward doubt. Stay ...",-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0
3,I've shifted my focus to something else but I'...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0
4,"I'm restless and restless, it's been a month n...",-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0

In [ ]:
del df_all1
del df_all2

In [10]:
# turn any value > 1 in whatever col into 1
for col in ["isSuspicious", "isRacist", "isSexist", "isHate", "isDepressive", "isSuicidal", "isAnxiety"]:
    df_all[col] = df_all[col].apply(lambda x: 1 if x > 1 else x)

## Print stat

In [11]:
num_samples = len(df_all)
print("Total number of samples:", num_samples)

Total number of samples: 69546

In [12]:
count_df = df_all[["isSuspicious", "isRacist", "isSexist", "isHate", "isDepressive", "isSuicidal", "isAnxiety"]].apply(pd.Series.value_counts).T
print("Label distribution:")
print(count_df)

Label distribution:
               -1.0    0.0    1.0
isSuspicious  31221  31110   7215
isRacist      31221  37380    945
isSexist      31221  36592   1733
isHate        31221  35647   2678
isDepressive  36649  18391  14506
isSuicidal    20009  37277  12260
isAnxiety     45652  18391   5503

## Helpers

In [13]:
from sklearn.model_selection import train_test_split
# split into train and test sets

# models bahaved rlly well, reduced train size to 20% to see if it can generalize better
# new note, NN at 20% still have liek 99% accuracy, reduced to 10% to intentionally handicap it
train_df, test_df = train_test_split(df_all, test_size=0.9, random_state=42)

In [ ]:
score_df = pd.DataFrame(columns=["model", "accuracy", "precision", "recall", "f1-score"])

In [15]:
from sklearn.metrics import classification_report, multilabel_confusion_matrix, accuracy_score, f1_score, precision_score, recall_score

def evaluate(
    model_name : str,
    preditor, # function from tensor of features (X) to list of predicted labels
    encoder, # function from list of texts to tensor of features (X)
    quiet : bool = False,

    X_test_encoded = None, # optional pre-encoded features for the test set, if already computed outside to save time
    df = test_df, # optional dataframe to use instead of the global test_df
):
    X = X_test_encoded if X_test_encoded is not None else encoder(df["text"].tolist()) 
    y_true = df[["isSuspicious", "isRacist", "isSexist", "isHate", "isDepressive", "isSuicidal", "isAnxiety"]].values
    y_pred = preditor(X)
    if len(y_pred) != len(y_true):
        # clamp both to the min
        min_len = min(len(y_pred), len(y_true))
        y_pred = y_pred[:min_len]
        y_true = y_true[:min_len]
    # For missing labels (-1), consider any prediction as correct
    missing_mask = y_true == -1
    y_true = y_true.astype(float)
    y_true[missing_mask] = y_pred[missing_mask]
    y_true = y_true.astype(int)
    # print classification report for each label
    # print multilabel confusion matrix for each label
    # print(multilabel_confusion_matrix(y_true, y_pred))
    # print overall accuracy, f1 score, precision, recall

    # fix y_pred mising values (somehow) with random 0 or 1
    mask_0 = y_pred != 0
    mask_1 = y_pred != 1
    mask = mask_0 & mask_1
    y_pred = np.where(mask, np.random.randint(0, 2, size=y_pred.shape), y_pred)

    accuracy = accuracy_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred, average="weighted", zero_division=0)
    precision = precision_score(y_true, y_pred, average="weighted", zero_division=0)
    recall = recall_score(y_true, y_pred, average="weighted", zero_division=0)
    score_df.loc[len(score_df)] = [model_name, accuracy, precision, recall, f1] # add to score_df

    if quiet:
        return

    print(classification_report(y_true, y_pred, target_names=["isSuspicious", "isRacist", "isSexist", "isHate", "isDepressive", "isSuicidal", "isAnxiety"], zero_division=0))
    print("Overall accuracy:", accuracy)
    print("Overall f1 score:", f1)
    print("Overall precision:", precision)
    print("Overall recall:", recall)

In [ ]:
import time
def fit_encoders(
    encoders, # list of encoders with fit methods
):
    time_start = time.time()
    for encoder in encoders:
        encoder.fit(train_df["text"].tolist())
    time_end = time.time()
    print(f"Encoders fit time: {time_end - time_start:.2f}s, averaged {(time_end - time_start) / len(encoders):.2f}s / encoder")

In [17]:
from sklearn.decomposition import PCA
ATTR_NAMES = ["isSuspicious", "isRacist", "isSexist", "isHate", "isDepressive", "isSuicidal", "isAnxiety"]

def random_missing_handler(Y):
    """Assign missing labels (-1) randomly to 0 or 1."""
    Y[Y == -1] = np.random.randint(0, 2, size=(Y == -1).sum())

def class_distribution_missing_handler(Y, bias_pos=0, bias_neg=15):
    """
    Assign missing labels based on observed class distribution for each label.
    bias_pos/bias_neg: optional bias toward positive/negative classes.
    """
    for col_idx in range(Y.shape[1]):
        col = Y[:, col_idx]
        known_mask = col != -1
        if known_mask.sum() > 0:
            # Calculate class distribution from known labels
            sum_pos = (col[known_mask] == 1).sum() + bias_pos
            sum_neg = (col[known_mask] == 0).sum() + bias_neg
            total = sum_pos + sum_neg
            if total > 0:
                p_pos = sum_pos / total
                p_neg = sum_neg / total
                missing_count = (col == -1).sum()
                if missing_count > 0:
                    Y[col == -1, col_idx] = np.random.choice([0, 1], size=missing_count, p=[p_neg, p_pos])
            else:
                # Fallback: random with equal probability
                missing_count = (col == -1).sum()
                if missing_count > 0:
                    Y[col == -1, col_idx] = np.random.choice([0, 1], size=missing_count, p=[0.5, 0.5])

def train_and_test(
    models, # list of (model_name, model (with predict method)),
    encoders, # list of (encoder_name, encoder models with at least transform (str -> tensor) as a method, assumed fitted already
    quiet : bool = False,

    # missing_handler(Y_train) modifies Y_train in place
    missing_handler = class_distribution_missing_handler,
    
    # Optional pre-encoded data to skip encoding
    X_train_encoded : dict = None,
    X_test_encoded : dict = None,

    forced_train_df = train_df, # optional dataframe to use instead of the global train_df
    forced_test_df = test_df, # optional dataframe to use instead of the global test_df

    pca_dim = None,
):
    # print("[DEBUG], starting train_and_test")
    train_df = forced_train_df
    test_df = forced_test_df
    # fit
    encoded = None # map from encoder_name to encoded X_train
    skip_precompute_encodings = X_train_encoded is not None
    if not skip_precompute_encodings:
        encoded = {}
        time_start = time.time()
        for encoder_name, encoder in encoders:
            encoded[encoder_name] = encoder.transform(train_df["text"].tolist())
        time_end = time.time()
        print(f"Encoded X_train with {len(encoders)} encoders in {time_end - time_start:.2f}s, averaged {(time_end - time_start) / len(encoders):.2f}s / encoder")
    else:
        # Use pre-encoded data if provided
        encoded = X_train_encoded

    # pca
    saved_pca = {}
    if pca_dim is not None:
        for encoder_name in encoded:
            # print(f"[DEBUG], encoded dim for encoder {encoder_name}: {encoded[encoder_name].shape[1]}, applying PCA to reduce to {pca_dim}")
            pca = PCA(n_components=pca_dim)
            encoded[encoder_name] = pca.fit_transform(encoded[encoder_name]) # add a new entry with PCA applied
            saved_pca[encoder_name] = pca

    # print("[DEBUG], finished pca encoding on train set")

    # Process Y_train with missing_handler
    Y_train = train_df[ATTR_NAMES].values
    missing_handler(Y_train)

    for model_name, model in models:
        print(f"Training model {model_name}")

        time_start = time.time()
        for encoder_name, encoder in encoders:
            X_train = encoded[encoder_name]

            model.fit(X_train, Y_train) # fit the model on the encoded X_train and Y_train

            def predictor(X):
                pca = None
                if pca_dim is not None and encoder_name in encoded:
                    pca = saved_pca[encoder_name]

                if X_test_encoded is not None and encoder_name in X_test_encoded:
                    X_encoded = X_test_encoded[encoder_name]
                    if pca is not None:
                        X_encoded = pca.transform(X_encoded)
                    return model.predict(X_encoded)
                else:
                    if isinstance(X, list):
                        X_encoded = encoder.transform(X)
                        X_encoded = X_encoded if pca is None else pca.transform(X_encoded)
                    else:
                        X_encoded = X
                    return model.predict(X_encoded)
            report_name = f"{model_name} ({encoder_name})" if pca_dim is None else f"{model_name} ({encoder_name} + PCA)"
            evaluate(report_name, predictor, lambda texts: texts, quiet=quiet, X_test_encoded=X_test_encoded, df=test_df)

        time_end = time.time()
        print(f"Evaluated {model_name} in {time_end - time_start:.2f}s")
        del model

## Dummy model

In [18]:
def random_predictor(X):
    if isinstance(X, torch.Tensor):
        X = X.cpu().numpy()
        num_samples = X.shape[0]
    else:
        if isinstance(X, list):
            num_samples = len(X)
    num_labels = 7
    return np.random.randint(2, size=(num_samples, num_labels))

def all_zero_predictor(X):
    if isinstance(X, torch.Tensor):
        X = X.cpu().numpy()
        num_samples = X.shape[0]
    else:
        if isinstance(X, list):
            num_samples = len(X)
    num_labels = 7
    return np.zeros((num_samples, num_labels), dtype=int)

def all_one_predictor(X):
    if isinstance(X, torch.Tensor):
        X = X.cpu().numpy()
        num_samples = X.shape[0]
    else:
        if isinstance(X, list):
            num_samples = len(X)
    num_labels = 7
    return np.ones((num_samples, num_labels), dtype=int)

evaluate("Random Predictor", random_predictor, lambda texts: texts,     quiet=True)
evaluate("All Zero Predictor", all_zero_predictor, lambda texts: texts, quiet=True)
evaluate("All One Predictor", all_one_predictor, lambda texts: texts,   quiet=True)
display(score_df)

                model  accuracy  precision    recall  f1-score
0    Random Predictor  0.236340   0.584595  0.858719  0.685429
1  All Zero Predictor  0.445648   0.000000  0.000000  0.000000
2   All One Predictor  0.449578   0.583041  1.000000  0.729307

## Classic models

This section will uses traditional encoders (TF-IDF and BOW) with Traditional models (Logistic regression and Decision tree)

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.multioutput import MultiOutputClassifier

In [20]:
N_FEAT = 5000

vectorizer_tfidf = TfidfVectorizer(max_features=N_FEAT)
vectorizer_BOW = CountVectorizer(max_features=N_FEAT)

print("Fitting encoders...")
fit_encoders([vectorizer_tfidf, vectorizer_BOW])

model_linear = MultiOutputClassifier(LogisticRegression(max_iter=1000))
model_decision_tree = MultiOutputClassifier(DecisionTreeClassifier())

# these 2 takes way too long for not a notable improvement, so we will ignore them for future tests
model_random_forest = MultiOutputClassifier(RandomForestClassifier())
model_svm = MultiOutputClassifier(SVC()) # especially SVM, which runs for close to 20 minutes

train_and_test(
    models=[
        ("Linear", model_linear),
        ("Decision Tree", model_decision_tree ),
        ("Random Forest", model_random_forest),
        ("SVM", model_svm),
    ],
    encoders=[
        ("TF-IDF", vectorizer_tfidf),
        ("BOW", vectorizer_BOW),
    ],
    quiet=True
)

Fitting encoders...
Encoders fit time: 0.45s, averaged 0.23s / encoder
Encoded X_train with 2 encoders in 0.40s, averaged 0.20s / encoder
Training model Linear
Evaluated Linear in 6.33s
Training model Decision Tree
Evaluated Decision Tree in 34.95s
Training model Random Forest
Evaluated Random Forest in 111.39s
Training model SVM
Evaluated SVM in 973.95s

In [21]:
# train with pca
train_and_test(
    models=[
        ("Linear", model_linear),
        ("Decision Tree", model_decision_tree),
    ],
    encoders=[
        ("TF-IDF", vectorizer_tfidf),
        ("BOW", vectorizer_BOW),
    ],
    quiet=True,
    pca_dim=100, # apply PCA to reduce dimensionality to 100
)

Encoded X_train with 2 encoders in 0.43s, averaged 0.22s / encoder
Training model Linear
Evaluated Linear in 7.48s
Training model Decision Tree
Evaluated Decision Tree in 28.49s

In [22]:
# dedup score_df by model name
score_df.drop_duplicates(subset=["model"], keep="first", inplace=True)
display(score_df.sort_values(by="f1-score", ascending=False))

                           model  accuracy  precision    recall  f1-score
6            Decision Tree (BOW)  0.659813   0.847433  0.799340  0.821739
5         Decision Tree (TF-IDF)  0.624105   0.824570  0.790322  0.805808
4                   Linear (BOW)  0.705490   0.915592  0.720670  0.802425
8            Random Forest (BOW)  0.741644   0.917154  0.725909  0.798338
9                   SVM (TF-IDF)  0.763053   0.957519  0.679100  0.768299
7         Random Forest (TF-IDF)  0.729950   0.932414  0.678852  0.767634
3                Linear (TF-IDF)  0.741660   0.954618  0.655575  0.745688
13  Decision Tree (TF-IDF + PCA)  0.508867   0.751973  0.729276  0.739476
14     Decision Tree (BOW + PCA)  0.489408   0.749451  0.730563  0.738931
2              All One Predictor  0.449578   0.583041  1.000000  0.729307
11         Linear (TF-IDF + PCA)  0.706848   0.926890  0.593963  0.686068
0               Random Predictor  0.236340   0.584595  0.858719  0.685429
10                     SVM (BOW)  0.729694   0.955765  0.607671  0.673201
12            Linear (BOW + PCA)  0.670709   0.963159  0.499923  0.604630
1             All Zero Predictor  0.445648   0.000000  0.000000  0.000000

## Recurrent Neural Net

In [23]:
import scipy.sparse as sp
def make_rnn_model(depth : int, in_dim, out_dim = 7, hidden_dim = 128, batch_size = 32, epochs = 5, lr = 0.001):    
    class SimpleRNN(nn.Module):
        def __init__(self):
            super(SimpleRNN, self).__init__()
            self.hidden_size = hidden_dim
            self.rnn_arr = nn.ModuleList([
                nn.RNN(in_dim if i == 0 else hidden_dim, hidden_dim, batch_first=True) for i in range(depth)
            ])
            self.fc = nn.Linear(hidden_dim, out_dim)
            self.epochs = epochs
            self.batch_size = batch_size
            self.lr = lr

        def fit(self, X, Y):
            # Convert sparse matrices to dense
            if sp.issparse(X):
                X = X.toarray()
            X = np.asarray(X)
            Y = np.asarray(Y)
            
            X_t = torch.tensor(X, dtype=torch.float32)
            Y_t = torch.tensor(Y, dtype=torch.float32)
            
            # Add sequence dimension: (batch_size, features) -> (batch_size, 1, features)
            if X_t.dim() == 2:
                X_t = X_t.unsqueeze(1)
            
            self.train()
            optimizer = torch.optim.Adam(self.parameters(), lr=self.lr)
            criterion = nn.BCEWithLogitsLoss()
            for epoch in range(self.epochs):
                optimizer.zero_grad()
                outputs = self.forward(X_t)
                loss = criterion(outputs, Y_t)
                loss.backward()
                optimizer.step()

        def predict(self, X):
            # Convert sparse matrices to dense
            if sp.issparse(X):
                X = X.toarray()
            X = np.asarray(X)
            
            X_t = torch.tensor(X, dtype=torch.float32)
            
            # Add sequence dimension
            if X_t.dim() == 2:
                X_t = X_t.unsqueeze(1)
            
            self.eval()
            with torch.no_grad():
                outputs = self.forward(X_t)
                return (torch.sigmoid(outputs) > 0.5).int().numpy()

        def forward(self, x):
            # x should be a tensor of shape (batch_size, seq_len, features)
            h = None
            for rnn in self.rnn_arr:
                x, h = rnn(x, h)
            # take the last output of the sequence
            x = x[:, -1, :]
            x = self.fc(x)
            return x

    return SimpleRNN()

In [24]:
rnn_model_d1 = make_rnn_model(depth=1, in_dim=N_FEAT)
rnn_model_d2 = make_rnn_model(depth=2, in_dim=N_FEAT)
rnn_model_d3 = make_rnn_model(depth=3, in_dim=N_FEAT)

train_and_test(
    models=[
        ("RNN Depth 1", rnn_model_d1),
        ("RNN Depth 2", rnn_model_d2),
        ("RNN Depth 3", rnn_model_d3),
    ],
    encoders=[
        ("TF-IDF", vectorizer_tfidf),
        ("BOW", vectorizer_BOW),
    ],
    quiet=True
)

Encoded X_train with 2 encoders in 0.40s, averaged 0.20s / encoder
Training model RNN Depth 1
Evaluated RNN Depth 1 in 17.21s
Training model RNN Depth 2
Evaluated RNN Depth 2 in 12.10s
Training model RNN Depth 3
Evaluated RNN Depth 3 in 12.75s

In [25]:
display(score_df.sort_values(by="f1-score", ascending=False))

                           model  accuracy  precision    recall  f1-score
6            Decision Tree (BOW)  0.659813   0.847433  0.799340  0.821739
5         Decision Tree (TF-IDF)  0.624105   0.824570  0.790322  0.805808
4                   Linear (BOW)  0.705490   0.915592  0.720670  0.802425
8            Random Forest (BOW)  0.741644   0.917154  0.725909  0.798338
9                   SVM (TF-IDF)  0.763053   0.957519  0.679100  0.768299
7         Random Forest (TF-IDF)  0.729950   0.932414  0.678852  0.767634
3                Linear (TF-IDF)  0.741660   0.954618  0.655575  0.745688
13  Decision Tree (TF-IDF + PCA)  0.508867   0.751973  0.729276  0.739476
14     Decision Tree (BOW + PCA)  0.489408   0.749451  0.730563  0.738931
2              All One Predictor  0.449578   0.583041  1.000000  0.729307
11         Linear (TF-IDF + PCA)  0.706848   0.926890  0.593963  0.686068
0               Random Predictor  0.236340   0.584595  0.858719  0.685429
10                     SVM (BOW)  0.729694   0.955765  0.607671  0.673201
12            Linear (BOW + PCA)  0.670709   0.963159  0.499923  0.604630
15          RNN Depth 1 (TF-IDF)  0.397495   0.499347  0.622453  0.531359
16             RNN Depth 1 (BOW)  0.470651   0.707274  0.570542  0.510066
18             RNN Depth 2 (BOW)  0.581065   0.645370  0.453257  0.448398
20             RNN Depth 3 (BOW)  0.578381   0.950398  0.393733  0.415124
1             All Zero Predictor  0.445648   0.000000  0.000000  0.000000
17          RNN Depth 2 (TF-IDF)  0.445648   0.000000  0.000000  0.000000
19          RNN Depth 3 (TF-IDF)  0.445648   0.000000  0.000000  0.000000

## Simple neural nets

In [26]:
import torch
from torch.utils.data import TensorDataset, DataLoader
import numpy as np
import scipy.sparse as sp

MAX_HIDDEN_SIZE = 128

# Wrapper to give a sklearn-like `fit`/`predict` interface to PyTorch models
def make_nn_model(depth : int, in_dim = N_FEAT, out_dim = 7, epochs=5, batch_size=32, lr=1e-3):
    class Wrapper:
        def __init__(self):
            layers = []
            last_dim = in_dim
            # build `depth` linear layers; ensure the final layer outputs `out_dim`
            for i in range(depth):
                if i == depth - 1:
                    new_out_dim = out_dim
                else:
                    # intermediate hidden size: half previous, but at least out_dim
                    new_out_dim = min(max(out_dim, last_dim // 2), MAX_HIDDEN_SIZE) # cap hidden size to prevent OOM and trains a bit faster
                print(f"Depth {depth} Layer {i}: {last_dim} -> {new_out_dim}")
                layers.append(nn.Linear(last_dim, new_out_dim))
                if i < depth - 1:
                    layers.append(nn.ReLU())
                else:
                    layers.append(nn.Sigmoid())
                last_dim = new_out_dim
            self.m = nn.Sequential(*layers)

        def fit(self, X, y):
            # handle scipy sparse matrices from vectorizers
            if sp.issparse(X):
                X = X.toarray()
            X = np.asarray(X)
            y = np.asarray(y)

            X_t = torch.tensor(X, dtype=torch.float32)
            y_t = torch.tensor(y, dtype=torch.float32)
            ds = TensorDataset(X_t, y_t)
            loader = DataLoader(ds, batch_size=batch_size, shuffle=True)
            opt = torch.optim.Adam(self.m.parameters(), lr=lr)
            loss_fn = torch.nn.BCELoss()
            self.m.train()
            for epoch in range(epochs):
                for xb, yb in loader:
                    opt.zero_grad()
                    out = self.m(xb)
                    loss = loss_fn(out, yb)
                    loss.backward()
                    opt.step()

        def predict(self, X):
            # handle scipy sparse matrices
            if sp.issparse(X):
                X = X.toarray()
            X = np.asarray(X)
            self.m.eval()
            with torch.no_grad():
                Xt = torch.tensor(X, dtype=torch.float32)
                out = self.m(Xt).numpy()
                return (out > 0.5).astype(int)

    return Wrapper()

# Create NN wrappers by depth
nn_model_depth1 = make_nn_model(depth=1)
nn_model_depth2 = make_nn_model(depth=2)
nn_model_depth3 = make_nn_model(depth=3)

models_to_use = [
    ("NN Depth 1", nn_model_depth1),
    ("NN Depth 2", nn_model_depth2),
    ("NN Depth 3", nn_model_depth3),
]

train_and_test(
    models=models_to_use,
    encoders=[
        ("TF-IDF", vectorizer_tfidf),
        ("BOW", vectorizer_BOW),
    ],
    quiet=True
)

# delete the NN models to free up GPU memory
del nn_model_depth1
del nn_model_depth2
del nn_model_depth3

Depth 1 Layer 0: 5000 -> 7
Depth 2 Layer 0: 5000 -> 128
Depth 2 Layer 1: 128 -> 7
Depth 3 Layer 0: 5000 -> 128
Depth 3 Layer 1: 128 -> 64
Depth 3 Layer 2: 64 -> 7
Encoded X_train with 2 encoders in 0.39s, averaged 0.20s / encoder
Training model NN Depth 1
Evaluated NN Depth 1 in 9.78s
Training model NN Depth 2
Evaluated NN Depth 2 in 18.46s
Training model NN Depth 3
Evaluated NN Depth 3 in 19.18s

In [27]:
NN_df = score_df
NN_df = NN_df.sort_values(by="f1-score", ascending=False)
display(NN_df)
# NN at depth 2 and 3 outperforms linear on TF-IDF but loses on BOW
# likely because BOW is more sparse and harder for NN to learn, while TF-IDF has more informative features that NN can leverag
# 2 is better than 3, likely due to 3 overfitting the small dataset, while 2 is a good balance of learning capacity and regularization

                           model  accuracy  precision    recall  f1-score
24              NN Depth 2 (BOW)  0.724470   0.883141  0.799078  0.836758
6            Decision Tree (BOW)  0.659813   0.847433  0.799340  0.821739
26              NN Depth 3 (BOW)  0.694961   0.857534  0.789483  0.820160
25           NN Depth 3 (TF-IDF)  0.718558   0.862483  0.786083  0.818248
5         Decision Tree (TF-IDF)  0.624105   0.824570  0.790322  0.805808
23           NN Depth 2 (TF-IDF)  0.755448   0.920737  0.736398  0.804344
4                   Linear (BOW)  0.705490   0.915592  0.720670  0.802425
8            Random Forest (BOW)  0.741644   0.917154  0.725909  0.798338
9                   SVM (TF-IDF)  0.763053   0.957519  0.679100  0.768299
7         Random Forest (TF-IDF)  0.729950   0.932414  0.678852  0.767634
3                Linear (TF-IDF)  0.741660   0.954618  0.655575  0.745688
13  Decision Tree (TF-IDF + PCA)  0.508867   0.751973  0.729276  0.739476
14     Decision Tree (BOW + PCA)  0.489408   0.749451  0.730563  0.738931
2              All One Predictor  0.449578   0.583041  1.000000  0.729307
22              NN Depth 1 (BOW)  0.717520   0.948179  0.610472  0.714278
11         Linear (TF-IDF + PCA)  0.706848   0.926890  0.593963  0.686068
0               Random Predictor  0.236340   0.584595  0.858719  0.685429
10                     SVM (BOW)  0.729694   0.955765  0.607671  0.673201
12            Linear (BOW + PCA)  0.670709   0.963159  0.499923  0.604630
15          RNN Depth 1 (TF-IDF)  0.397495   0.499347  0.622453  0.531359
16             RNN Depth 1 (BOW)  0.470651   0.707274  0.570542  0.510066
18             RNN Depth 2 (BOW)  0.581065   0.645370  0.453257  0.448398
21           NN Depth 1 (TF-IDF)  0.603208   0.665420  0.405473  0.443044
20             RNN Depth 3 (BOW)  0.578381   0.950398  0.393733  0.415124
1             All Zero Predictor  0.445648   0.000000  0.000000  0.000000
17          RNN Depth 2 (TF-IDF)  0.445648   0.000000  0.000000  0.000000
19          RNN Depth 3 (TF-IDF)  0.445648   0.000000  0.000000  0.000000

## Sentence embedding as encoders

### BERT (Distilled)

In [28]:
!pip install --quiet --no-warn-script-location xformers trl
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# Load pre-trained BERT model and tokenizer
model_name = "distilbert-base-uncased"
bert_tokenizer = AutoTokenizer.from_pretrained(model_name)
bert_model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=7)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:122: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [29]:
# test
time_start = time.time()

text = "Hello, this is a test tweet to check if the BERT model can process it without errors."

class_inputs = bert_tokenizer([text], padding=True, truncation=True, return_tensors="pt")
outputs = bert_model(**class_inputs)
print("BERT output logits shape", outputs.logits.shape)
time_end = time.time()
print(f"Tested BERT in {time_end - time_start:.2f}s")

BERT output logits shape torch.Size([1, 7])
Tested BERT in 0.22s

In [ ]:
def batch_encode_bert_single(texts, i, batch_size):
    batch_texts = texts[i:i+batch_size]
    inputs = bert_tokenizer(batch_texts, padding=True, truncation=True, return_tensors="pt")
    with torch.no_grad():
        outputs = bert_model(**inputs)
    return outputs.logits.cpu().numpy()

In [ ]:
# Commented out
# for bs in [8, 16, 32]:
#     time_start = time.time()
#     batch_encode_bert_single(test_df["text"].tolist(), 0, bs)
#     time_end = time.time()
#     print(f"BERT encoded 1 batch of size {bs} in {time_end - time_start:.2f}s, extrapolated to full test set: {(time_end - time_start) * (len(test_df) / bs):.2f}s")

In [35]:
# BERT is hella slow, even the distilled version

# we use 100 samples for train, 500 for test

FORCED_TRAIN_SIZE = 100
FORCED_TEST_SIZE = 500
bs = 8

new_train_indices = np.random.choice(train_df.index, size=FORCED_TRAIN_SIZE, replace=True)
new_test_indices = np.random.choice(test_df.index, size=FORCED_TEST_SIZE, replace=True)

bert_train_df = train_df.loc[new_train_indices].reset_index(drop=True)
bert_test_df = test_df.loc[new_test_indices].reset_index(drop=True)

# encode
bert_train_encodings = []
for i in range(0, FORCED_TRAIN_SIZE, bs):
    batch_encodings = batch_encode_bert_single(bert_train_df["text"].tolist(), i, bs)
    bert_train_encodings.append(batch_encodings)
    # progress print
    progress = min(i + bs, FORCED_TRAIN_SIZE) / FORCED_TRAIN_SIZE * 100
    print(f"Encoded {min(i + bs, FORCED_TRAIN_SIZE)} / {FORCED_TRAIN_SIZE} train samples ({progress:.2f}%)", end="\r")

print()
bert_train_encodings = np.vstack(bert_train_encodings)

bert_test_encodings = []
for i in range(0, FORCED_TEST_SIZE, bs):
    batch_encodings = batch_encode_bert_single(bert_test_df["text"].tolist(), i, bs)
    bert_test_encodings.append(batch_encodings)
    # progress print
    progress = min(i + bs, FORCED_TEST_SIZE) / FORCED_TEST_SIZE * 100
    print(f"Encoded {min(i + bs, FORCED_TEST_SIZE)} / {FORCED_TEST_SIZE} test samples ({progress:.2f}%)", end="\r")

print()
bert_test_encodings = np.vstack(bert_test_encodings)

Encoded 100 / 100 train samples (100.00%)
Encoded 500 / 500 test samples (100.00%)

In [36]:
EMBED_DIM = bert_train_encodings.shape[1]
print("BERT embedding dimension:", EMBED_DIM)

nn_model_bert1 = make_nn_model(depth=1, in_dim=EMBED_DIM)
nn_model_bert2 = make_nn_model(depth=2, in_dim=EMBED_DIM)
nn_model_bert3 = make_nn_model(depth=3, in_dim=EMBED_DIM)

rnn_model_bert1 = make_rnn_model(depth=1, in_dim=EMBED_DIM)
rnn_model_bert2 = make_rnn_model(depth=2, in_dim=EMBED_DIM)
rnn_model_bert3 = make_rnn_model(depth=3, in_dim=EMBED_DIM)

train_and_test(
    models=[
        ("Linear_a", model_linear),
        ("Decision Tree", model_decision_tree),
        ("NN Depth 1", nn_model_bert1),
        ("NN Depth 2", nn_model_bert2),
        ("NN Depth 3", nn_model_bert3),
        ("RNN Depth 1", rnn_model_bert1),
        ("RNN Depth 2", rnn_model_bert2),
        ("RNN Depth 3", rnn_model_bert3),
    ],
    encoders=[
        ("Distilled BERT", None), 
    ],
    quiet=True,
    X_train_encoded={"Distilled BERT": bert_train_encodings},
    X_test_encoded={"Distilled BERT": bert_test_encodings},
    forced_train_df=bert_train_df,
    forced_test_df=bert_test_df,
)

BERT embedding dimension: 7
Depth 1 Layer 0: 7 -> 7
Depth 2 Layer 0: 7 -> 7
Depth 2 Layer 1: 7 -> 7
Depth 3 Layer 0: 7 -> 7
Depth 3 Layer 1: 7 -> 7
Depth 3 Layer 2: 7 -> 7
Training model Linear_a
Evaluated Linear_a in 0.03s
Training model Decision Tree
Evaluated Decision Tree in 0.02s
Training model NN Depth 1
Evaluated NN Depth 1 in 0.03s
Training model NN Depth 2
Evaluated NN Depth 2 in 0.03s
Training model NN Depth 3
Evaluated NN Depth 3 in 0.03s
Training model RNN Depth 1
Evaluated RNN Depth 1 in 0.02s
Training model RNN Depth 2
Evaluated RNN Depth 2 in 0.02s
Training model RNN Depth 3
Evaluated RNN Depth 3 in 0.02s

In [37]:
# score_df.drop_duplicates(subset=["model"], keep="first", inplace=True)
display(score_df.sort_values(by="f1-score", ascending=False))

                             model  accuracy  precision    recall  f1-score
24                NN Depth 2 (BOW)  0.724470   0.883141  0.799078  0.836758
6              Decision Tree (BOW)  0.659813   0.847433  0.799340  0.821739
26                NN Depth 3 (BOW)  0.694961   0.857534  0.789483  0.820160
25             NN Depth 3 (TF-IDF)  0.718558   0.862483  0.786083  0.818248
5           Decision Tree (TF-IDF)  0.624105   0.824570  0.790322  0.805808
23             NN Depth 2 (TF-IDF)  0.755448   0.920737  0.736398  0.804344
4                     Linear (BOW)  0.705490   0.915592  0.720670  0.802425
8              Random Forest (BOW)  0.741644   0.917154  0.725909  0.798338
9                     SVM (TF-IDF)  0.763053   0.957519  0.679100  0.768299
7           Random Forest (TF-IDF)  0.729950   0.932414  0.678852  0.767634
3                  Linear (TF-IDF)  0.741660   0.954618  0.655575  0.745688
13    Decision Tree (TF-IDF + PCA)  0.508867   0.751973  0.729276  0.739476
14       Decision Tree (BOW + PCA)  0.489408   0.749451  0.730563  0.738931
29     NN Depth 1 (Distilled BERT)  0.314000   0.609085  0.924352  0.730188
2                All One Predictor  0.449578   0.583041  1.000000  0.729307
22                NN Depth 1 (BOW)  0.717520   0.948179  0.610472  0.714278
31     NN Depth 3 (Distilled BERT)  0.332000   0.565807  0.937500  0.701642
11           Linear (TF-IDF + PCA)  0.706848   0.926890  0.593963  0.686068
0                 Random Predictor  0.236340   0.584595  0.858719  0.685429
10                       SVM (BOW)  0.729694   0.955765  0.607671  0.673201
28  Decision Tree (Distilled BERT)  0.394000   0.670845  0.666084  0.665454
12              Linear (BOW + PCA)  0.670709   0.963159  0.499923  0.604630
30     NN Depth 2 (Distilled BERT)  0.128000   0.494217  0.738789  0.590164
34    RNN Depth 3 (Distilled BERT)  0.402000   0.487189  0.658363  0.559987
15            RNN Depth 1 (TF-IDF)  0.397495   0.499347  0.622453  0.531359
16               RNN Depth 1 (BOW)  0.470651   0.707274  0.570542  0.510066
18               RNN Depth 2 (BOW)  0.581065   0.645370  0.453257  0.448398
21             NN Depth 1 (TF-IDF)  0.603208   0.665420  0.405473  0.443044
20               RNN Depth 3 (BOW)  0.578381   0.950398  0.393733  0.415124
32    RNN Depth 1 (Distilled BERT)  0.180000   0.283047  0.542553  0.367511
1               All Zero Predictor  0.445648   0.000000  0.000000  0.000000
17            RNN Depth 2 (TF-IDF)  0.445648   0.000000  0.000000  0.000000
19            RNN Depth 3 (TF-IDF)  0.445648   0.000000  0.000000  0.000000
27       Linear_a (Distilled BERT)  0.422000   0.000000  0.000000  0.000000
33    RNN Depth 2 (Distilled BERT)  0.422000   0.000000  0.000000  0.000000

### Word2Vec

In [38]:
# Word2Vec

# moved the import here to avoid OOM for BERT
!pip install gensim
from gensim.models import Word2Vec
# Note, I failed to get GloVe working, so I will skip it for now
# BERT should outperform both Word2Vec and GloVe in theory

class Word2Vec_encoder:
    def __init__(self, vector_size=1000):
        self.vector_size = vector_size
        self.model = None

    def fit(self, texts):
        tokenized = [text.split() for text in texts]
        self.model = Word2Vec(sentences=tokenized, vector_size=self.vector_size, window=5, min_count=1, workers=4)

    def transform(self, texts):
        tokenized = [text.split() for text in texts]
        embeddings = []
        for tokens in tokenized:
            token_vecs = []
            for token in tokens:
                if token in self.model.wv:
                    token_vecs.append(self.model.wv[token])
            if token_vecs:
                embeddings.append(np.mean(token_vecs, axis=0))
            else:
                embeddings.append(np.zeros(self.vector_size))
        
        # Use vstack to properly handle array creation
        if embeddings:
            return np.vstack(embeddings)
        else:
            return np.array([]).reshape(0, self.vector_size)
    
word2vec_encoder = Word2Vec_encoder(vector_size=1000)
word2vec_encoder.fit(train_df["text"].tolist())

Requirement already satisfied: gensim in /usr/local/lib/python3.12/dist-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.2.1)

In [39]:
NN_1_word2vec = make_nn_model(depth=1, in_dim=1000)
NN_2_word2vec = make_nn_model(depth=2, in_dim=1000)
NN_3_word2vec = make_nn_model(depth=3, in_dim=1000)

RNN_1_word2vec = make_rnn_model(depth=1, in_dim=1000)
RNN_2_word2vec = make_rnn_model(depth=2, in_dim=1000)
RNN_3_word2vec = make_rnn_model(depth=3, in_dim=1000)

train_and_test(
    models=[
        ("NN Depth 1", NN_1_word2vec),
        ("NN Depth 2", NN_2_word2vec),
        ("NN Depth 3", NN_3_word2vec),

        ("RNN Depth 1", RNN_1_word2vec),
        ("RNN Depth 2", RNN_2_word2vec),
        ("RNN Depth 3", RNN_3_word2vec),
        
        ("Linear", model_linear),
        ("Decision Tree", model_decision_tree),
    ],
    encoders=[
        ("Word2Vec", word2vec_encoder),
    ],
    quiet=True
)

Depth 1 Layer 0: 1000 -> 7
Depth 2 Layer 0: 1000 -> 128
Depth 2 Layer 1: 128 -> 7
Depth 3 Layer 0: 1000 -> 128
Depth 3 Layer 1: 128 -> 64
Depth 3 Layer 2: 64 -> 7
Encoded X_train with 1 encoders in 0.85s, averaged 0.85s / encoder
Training model NN Depth 1
Evaluated NN Depth 1 in 9.91s
Training model NN Depth 2
Evaluated NN Depth 2 in 10.03s
Training model NN Depth 3
Evaluated NN Depth 3 in 10.02s
Training model RNN Depth 1
Evaluated RNN Depth 1 in 9.08s
Training model RNN Depth 2
Evaluated RNN Depth 2 in 8.44s
Training model RNN Depth 3
Evaluated RNN Depth 3 in 9.64s
Training model Linear
Evaluated Linear in 12.85s
Training model Decision Tree
Evaluated Decision Tree in 119.96s

In [40]:
# train with pca
EMBED_DIM = 100
NN_1_word2vec = make_nn_model(depth=1, in_dim=EMBED_DIM)
NN_2_word2vec = make_nn_model(depth=2, in_dim=EMBED_DIM)
NN_3_word2vec = make_nn_model(depth=3, in_dim=EMBED_DIM)

RNN_1_word2vec = make_rnn_model(depth=1, in_dim=EMBED_DIM)
RNN_2_word2vec = make_rnn_model(depth=2, in_dim=EMBED_DIM)
RNN_3_word2vec = make_rnn_model(depth=3, in_dim=EMBED_DIM)

train_and_test(
    models=[
        ("NN Depth 1", NN_1_word2vec),
        ("NN Depth 2", NN_2_word2vec),
        ("NN Depth 3", NN_3_word2vec),

        ("RNN Depth 1", RNN_1_word2vec),
        ("RNN Depth 2", RNN_2_word2vec),
        ("RNN Depth 3", RNN_3_word2vec),
        
        ("Linear", model_linear),
        ("Decision Tree", model_decision_tree),
    ],
    encoders=[
        ("Word2Vec", word2vec_encoder),
    ],
    quiet=True,
    pca_dim=EMBED_DIM
)

Depth 1 Layer 0: 100 -> 7
Depth 2 Layer 0: 100 -> 50
Depth 2 Layer 1: 50 -> 7
Depth 3 Layer 0: 100 -> 50
Depth 3 Layer 1: 50 -> 25
Depth 3 Layer 2: 25 -> 7
Encoded X_train with 1 encoders in 0.89s, averaged 0.89s / encoder
Training model NN Depth 1
Evaluated NN Depth 1 in 9.34s
Training model NN Depth 2
Evaluated NN Depth 2 in 9.10s
Training model NN Depth 3
Evaluated NN Depth 3 in 9.60s
Training model RNN Depth 1
Evaluated RNN Depth 1 in 9.11s
Training model RNN Depth 2
Evaluated RNN Depth 2 in 8.93s
Training model RNN Depth 3
Evaluated RNN Depth 3 in 8.65s
Training model Linear
Evaluated Linear in 10.60s
Training model Decision Tree
Evaluated Decision Tree in 17.88s

In [41]:
display(score_df.sort_values(by="f1-score", ascending=False))
# Word2Vec performs much worse than TF-IDF and BOW, 
# likely because the dataset is small and/or highly specialized and Word2Vec doesnt provide good enough contextua embedding, while TF-IDF and BOW can still extract useful features based on word frequency.
# this may indicate context sensitive embedding is not very useful for this dataset, and simple frequency based features are more effective
# We continue with gpt2 anyway to verify this hypothesis

                             model  accuracy  precision    recall  f1-score
24                NN Depth 2 (BOW)  0.724470   0.883141  0.799078  0.836758
6              Decision Tree (BOW)  0.659813   0.847433  0.799340  0.821739
26                NN Depth 3 (BOW)  0.694961   0.857534  0.789483  0.820160
25             NN Depth 3 (TF-IDF)  0.718558   0.862483  0.786083  0.818248
5           Decision Tree (TF-IDF)  0.624105   0.824570  0.790322  0.805808
23             NN Depth 2 (TF-IDF)  0.755448   0.920737  0.736398  0.804344
4                     Linear (BOW)  0.705490   0.915592  0.720670  0.802425
8              Random Forest (BOW)  0.741644   0.917154  0.725909  0.798338
9                     SVM (TF-IDF)  0.763053   0.957519  0.679100  0.768299
7           Random Forest (TF-IDF)  0.729950   0.932414  0.678852  0.767634
3                  Linear (TF-IDF)  0.741660   0.954618  0.655575  0.745688
13    Decision Tree (TF-IDF + PCA)  0.508867   0.751973  0.729276  0.739476
14       Decision Tree (BOW + PCA)  0.489408   0.749451  0.730563  0.738931
29     NN Depth 1 (Distilled BERT)  0.314000   0.609085  0.924352  0.730188
2                All One Predictor  0.449578   0.583041  1.000000  0.729307
22                NN Depth 1 (BOW)  0.717520   0.948179  0.610472  0.714278
31     NN Depth 3 (Distilled BERT)  0.332000   0.565807  0.937500  0.701642
50  Decision Tree (Word2Vec + PCA)  0.420597   0.678426  0.728290  0.700831
42        Decision Tree (Word2Vec)  0.417657   0.673806  0.732999  0.700158
11           Linear (TF-IDF + PCA)  0.706848   0.926890  0.593963  0.686068
0                 Random Predictor  0.236340   0.584595  0.858719  0.685429
10                       SVM (BOW)  0.729694   0.955765  0.607671  0.673201
28  Decision Tree (Distilled BERT)  0.394000   0.670845  0.666084  0.665454
45     NN Depth 3 (Word2Vec + PCA)  0.665548   0.655889  0.638562  0.645885
44     NN Depth 2 (Word2Vec + PCA)  0.640274   0.642680  0.594052  0.615245
37           NN Depth 3 (Word2Vec)  0.629298   0.642577  0.585417  0.609593
12              Linear (BOW + PCA)  0.670709   0.963159  0.499923  0.604630
36           NN Depth 2 (Word2Vec)  0.611516   0.636318  0.573945  0.596411
30     NN Depth 2 (Distilled BERT)  0.128000   0.494217  0.738789  0.590164
49         Linear (Word2Vec + PCA)  0.610222   0.720213  0.555263  0.584820
41               Linear (Word2Vec)  0.606675   0.729706  0.549291  0.580792
43     NN Depth 1 (Word2Vec + PCA)  0.597329   0.655368  0.535994  0.565167
46    RNN Depth 1 (Word2Vec + PCA)  0.134394   0.584937  0.660086  0.564055
34    RNN Depth 3 (Distilled BERT)  0.402000   0.487189  0.658363  0.559987
47    RNN Depth 2 (Word2Vec + PCA)  0.481659   0.622555  0.584764  0.546448
15            RNN Depth 1 (TF-IDF)  0.397495   0.499347  0.622453  0.531359
16               RNN Depth 1 (BOW)  0.470651   0.707274  0.570542  0.510066
18               RNN Depth 2 (BOW)  0.581065   0.645370  0.453257  0.448398
21             NN Depth 1 (TF-IDF)  0.603208   0.665420  0.405473  0.443044
20               RNN Depth 3 (BOW)  0.578381   0.950398  0.393733  0.415124
48    RNN Depth 3 (Word2Vec + PCA)  0.521440   0.505175  0.410794  0.407263
35           NN Depth 1 (Word2Vec)  0.512749   0.588258  0.307042  0.390615
32    RNN Depth 1 (Distilled BERT)  0.180000   0.283047  0.542553  0.367511
38          RNN Depth 1 (Word2Vec)  0.434592   0.077741  0.013647  0.023072
39          RNN Depth 2 (Word2Vec)  0.433027   0.019489  0.002943  0.005114
17            RNN Depth 2 (TF-IDF)  0.445648   0.000000  0.000000  0.000000
1               All Zero Predictor  0.445648   0.000000  0.000000  0.000000
33    RNN Depth 2 (Distilled BERT)  0.422000   0.000000  0.000000  0.000000
27       Linear_a (Distilled BERT)  0.422000   0.000000  0.000000  0.000000
19            RNN Depth 3 (TF-IDF)  0.445648   0.000000  0.000000  0.000000
40          RNN Depth 3 (Word2Vec)  0.445648   0.000000  0.000000  0.000000

## LLM as encoders

In [42]:
# GPT2
from transformers import GPT2Tokenizer, GPT2Model

tokenizer_gpt2 = GPT2Tokenizer.from_pretrained("gpt2")
model_gpt2 = GPT2Model.from_pretrained("gpt2")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

In [43]:
# test
start_time = time.time()


text = "This is a test sentence for GPT-2 encoding."
class_inputs = tokenizer_gpt2(text, return_tensors="pt")
logits = model_gpt2(**class_inputs).last_hidden_state.mean(dim=1).detach().numpy()

print("GPT-2 encoding shape:", logits.shape)
end_time = time.time()

print(f"GPT-2 encoding time: {end_time - start_time:.2f}s")

GPT-2 encoding shape: (1, 768)
GPT-2 encoding time: 0.59s

In [44]:
# test batch encoding
tokenizer_gpt2.pad_token = tokenizer_gpt2.eos_token # set pad token to eos token
def single_batch_encoding(texts, i, batch_size=32, max_length=512):
    batch_texts = texts[i:i+batch_size]
    inputs = tokenizer_gpt2(batch_texts, return_tensors="pt", padding=True, truncation=True, max_length=max_length)
    with torch.no_grad():
        logits = model_gpt2(**inputs).last_hidden_state.mean(dim=1).numpy()
    return logits

In [45]:
# for bs in [8, 16, 32, 64]:
#     start_time = time.time()
#     batch_logits = single_batch_encoding(train_df["text"].tolist(), 0, batch_size=bs, max_length=50)
#     end_time = time.time()
#     print(f"GPT-2 encoding time with batch size {bs}: {end_time - start_time:.2f}s, expected {(end_time - start_time) * (len(train_df) / bs):.2f}s for full dataset")

In [46]:
# GPT-2 is faster than BERT distilled somehow

FORCED_TRAIN_SIZE = 100 # train on all available training samples to ensure sufficient class diversity
BATCH_SIZE = 16

new_train_indices = np.random.choice(train_df.index, size=FORCED_TRAIN_SIZE, replace=False)
gpt2_train_df = train_df.loc[new_train_indices].reset_index(drop=True)

new_test_indices = np.random.choice(test_df.index, size=FORCED_TRAIN_SIZE * 10, replace=False)
gpt2_test_df = test_df.loc[new_test_indices].reset_index(drop=True)

# encode the full train and test sets
encoded_train_gpt2 = []
for i in range(0, FORCED_TRAIN_SIZE, BATCH_SIZE):
    batch_logits = single_batch_encoding(gpt2_train_df["text"].tolist(), i, batch_size=BATCH_SIZE, max_length=50)
    encoded_train_gpt2.append(batch_logits)
    # print progress
    progress = min(i + BATCH_SIZE, FORCED_TRAIN_SIZE) / FORCED_TRAIN_SIZE * 100
    print(f"Encoded {min(i + BATCH_SIZE, FORCED_TRAIN_SIZE)} / {FORCED_TRAIN_SIZE} ({progress:.2f}%)", end="\r")

print()
FORCED_TEST_SIZE = FORCED_TRAIN_SIZE * 10 # encode 1120 samples for testing
encoded_test_gpt2 = []
for i in range(0, FORCED_TEST_SIZE, BATCH_SIZE):
    batch_logits = single_batch_encoding(gpt2_test_df["text"].tolist(), i, batch_size=BATCH_SIZE, max_length=50)
    encoded_test_gpt2.append(batch_logits)
    # print progress
    progress = min(i + BATCH_SIZE, FORCED_TEST_SIZE) / FORCED_TEST_SIZE * 100
    print(f"Encoded {min(i + BATCH_SIZE, FORCED_TEST_SIZE)} / {FORCED_TEST_SIZE} ({progress:.2f}%)", end="\r")

print()

Encoded 100 / 100 (100.00%)
Encoded 1000 / 1000 (100.00%)

In [47]:
# linear failed to converged, we do some scaling
linear_scaling_factor = 10
model_linear_scaled = MultiOutputClassifier(LogisticRegression(max_iter=5000, C=linear_scaling_factor))

EMBED_DIM = 768 # GPT-2 base hidden size
nn_depth1 = make_nn_model(depth=1, in_dim=EMBED_DIM, epochs=10, lr=1e-4)
nn_depth2 = make_nn_model(depth=2, in_dim=EMBED_DIM, epochs=10, lr=1e-4)
nn_depth3 = make_nn_model(depth=3, in_dim=EMBED_DIM, epochs=10, lr=1e-4)

rnn_bert1 = make_rnn_model(depth=1, in_dim=EMBED_DIM, epochs=10, lr=1e-4)
rnn_bert2 = make_rnn_model(depth=2, in_dim=EMBED_DIM, epochs=10, lr=1e-4)
rnn_bert3 = make_rnn_model(depth=3, in_dim=EMBED_DIM, epochs=10, lr=1e-4)

train_and_test(
    models=[
        ("Linear", model_linear_scaled),
        ("Decision Tree", model_decision_tree),
        ("NN Depth 1", nn_depth1),
        ("NN Depth 2", nn_depth2),
        ("NN Depth 3", nn_depth3),
        ("RNN Depth 1", rnn_bert1),
        ("RNN Depth 2", rnn_bert2),
        ("RNN Depth 3", rnn_bert3),
    ],
    encoders=[
        ("GPT-2", None), # pass None since we are pre-encoding the data, and predictor will use the pre-encoded data directly
    ],
    quiet=True,
    X_train_encoded={"GPT-2": np.vstack(encoded_train_gpt2)}, # pass pre-encoded data to skip encoding again
    X_test_encoded={"GPT-2": np.vstack(encoded_test_gpt2)}, # pass pre-encoded data to skip encoding again
    forced_train_df = gpt2_train_df, # use the new smaller train set
    forced_test_df = gpt2_test_df, # use the new smaller test set
)

Depth 1 Layer 0: 768 -> 7
Depth 2 Layer 0: 768 -> 128
Depth 2 Layer 1: 128 -> 7
Depth 3 Layer 0: 768 -> 128
Depth 3 Layer 1: 128 -> 64
Depth 3 Layer 2: 64 -> 7
Training model Linear
Evaluated Linear in 1.72s
Training model Decision Tree
Evaluated Decision Tree in 0.30s
Training model NN Depth 1
Evaluated NN Depth 1 in 0.04s
Training model NN Depth 2
Evaluated NN Depth 2 in 0.06s
Training model NN Depth 3
Evaluated NN Depth 3 in 0.07s
Training model RNN Depth 1
Evaluated RNN Depth 1 in 0.03s
Training model RNN Depth 2
Evaluated RNN Depth 2 in 0.04s
Training model RNN Depth 3
Evaluated RNN Depth 3 in 0.05s

In [48]:
# train with pca
EMBED_DIM = 100
nn_depth1 = make_nn_model(depth=1, in_dim=EMBED_DIM, epochs=10, lr=1e-4)
nn_depth2 = make_nn_model(depth=2, in_dim=EMBED_DIM, epochs=10, lr=1e-4)
nn_depth3 = make_nn_model(depth=3, in_dim=EMBED_DIM, epochs=10, lr=1e-4)

rnn_bert1 = make_rnn_model(depth=1, in_dim=EMBED_DIM, epochs=10, lr=1e-4)
rnn_bert2 = make_rnn_model(depth=2, in_dim=EMBED_DIM, epochs=10, lr=1e-4)
rnn_bert3 = make_rnn_model(depth=3, in_dim=EMBED_DIM, epochs=10, lr=1e-4)

train_and_test(
    models=[
        ("Linear", model_linear_scaled),
        ("Decision Tree", model_decision_tree),
        ("NN Depth 1", nn_depth1),
        ("NN Depth 2", nn_depth2),
        ("NN Depth 3", nn_depth3),
        ("RNN Depth 1", rnn_bert1),
        ("RNN Depth 2", rnn_bert2),
        ("RNN Depth 3", rnn_bert3),
    ],
    encoders=[
        ("GPT-2", None), # pass None since we are pre-encoding the data, and predictor will use the pre-encoded data directly
    ],
    quiet=True,
    X_train_encoded={"GPT-2": np.vstack(encoded_train_gpt2)}, # pass pre-encoded data to skip encoding again
    X_test_encoded={"GPT-2": np.vstack(encoded_test_gpt2)}, # pass pre-encoded data to skip encoding again
    forced_train_df = gpt2_train_df, # use the new smaller train set
    forced_test_df = gpt2_test_df, # use the new smaller test set
    pca_dim=EMBED_DIM
)

Depth 1 Layer 0: 100 -> 7
Depth 2 Layer 0: 100 -> 50
Depth 2 Layer 1: 50 -> 7
Depth 3 Layer 0: 100 -> 50
Depth 3 Layer 1: 50 -> 25
Depth 3 Layer 2: 25 -> 7
Training model Linear
Evaluated Linear in 0.18s
Training model Decision Tree
Evaluated Decision Tree in 0.07s
Training model NN Depth 1
Evaluated NN Depth 1 in 0.07s
Training model NN Depth 2
Evaluated NN Depth 2 in 0.06s
Training model NN Depth 3
Evaluated NN Depth 3 in 0.06s
Training model RNN Depth 1
Evaluated RNN Depth 1 in 0.03s
Training model RNN Depth 2
Evaluated RNN Depth 2 in 0.04s
Training model RNN Depth 3
Evaluated RNN Depth 3 in 0.05s

## Embedding models as zero shot predictors

In [49]:
Prompts_Descriptive_Sentences = [
    # class 1, isSuspicious
    ("This is a normal tweet.",            
     "This tweet contains harmful content and should be flagged, can contain contents that are racist, sexist, hateful, or suicidal."),
    # class 2, isRacist
    ("This is a normal tweet.",
     "This tweet contains racist content and should be flagged, can contain discriminatory or derogatory language targeting specific races like asian, black, etc."),
    # class 3, isSexist
    ("This is a normal tweet.",
     "This tweet contains sexist content and should be flagged, can contain discriminatory or derogatory language targeting man or women."),
    # class 4, isHate
    ("This is a normal tweet.",
     "This tweet contains hateful content and should be flagged, can contain language that promotes violence or hatred against individuals or groups based on attributes like race, religion, gender, beliefs, etc."),
    # class 5, isDepressive
    ("This is a normal tweet.",
     "This tweet contains depressive content and should be flagged, can contain language that expresses feelings of sadness, hopelessness, or worthlessness."),
    # class 6, isSuicidal
    ("This is a normal tweet.",
     "This tweet contains suicidal content and should be flagged, can contain language that expresses thoughts of self-harm or the desire to end one's own life."),
    # class 7, isAnxiety
    ("This is a normal tweet.",
     "This tweet contains anxiety content and should be flagged, can contain language that expresses excessive worry, fear, or nervousness."),
]

Prompts_Single_Word = [
    # class 1, isSuspicious
    ("Normal", "Suspicious"),
    # class 2, isRacist
    ("Normal", "Racist"),
    # class 3, isSexist
    ("Normal", "Sexist"),
    # class 4, isHate
    ("Normal", "Hateful"),
    # class 5, isDepressive
    ("Normal", "Depressive"),
    # class 6, isSuicidal
    ("Normal", "Suicidal"),
    # class 7, isAnxiety
    ("Normal", "Anxiety"),
]

Prompts_Wordset = [
    # class 1, isSuspicious
    ("Normal", "Suspicious, harmful, dangerous"),
    # class 2, isRacist
    ("Normal", "Racist, Racism, discriminatory, minority, asian, black"),
    # class 3, isSexist
    ("Normal", "Sexist, Sexism, discriminatory, male, female, man, women"),
    # class 4, isHate
    ("Normal", "Hate, hateful, hatespeech, violence"),
    # class 5, isDepressive
    ("Normal", "Depressive, depression, sad, hopeless, worthless"),
    # class 6, isSuicidal
    ("Normal", "Suicidal, die, death, self-harm, end life"),
    # class 7, isAnxiety
    ("Normal", "Anxiety, anxious, worry, fear, nervous, panic"),
]

class ZeroShotModel_projectionBased:
    # we have 2 points, the center of "good" and the center of "bad"
    # from good to bad we have a vector
    # we project the embedding onto this vector, and if the projection is closer to the bad center than the good center, we predict 1, else 0
    def __init__(self):
        pass

    def fit(self, X, Y):
        # calc centers
        # assume encoded already
        self.good_centers = []
        self.bad_centers = []
        for axis in range(Y.shape[1]):
            good_samples = X[Y[:, axis] == 0]
            bad_samples  = X[Y[:, axis] == 1]

            center_good = np.mean(good_samples, axis=0)
            center_bad  = np.mean(bad_samples, axis=0)

            self.good_centers.append(center_good)
            self.bad_centers.append(center_bad)

    def predict(self, X):
        predictions = []
        for x in X:
            sample_preds = []
            for good_center, bad_center in zip(self.good_centers, self.bad_centers):
                vec = bad_center - good_center
                projection = np.dot(x - good_center, vec) / (np.linalg.norm(vec) + 1e-8)
                pred = 1 if projection > 0 else 0
                sample_preds.append(pred)
            predictions.append(sample_preds)
        return np.array(predictions)


class ZeroShotModel_promptBased:
    def __init__(self, tokenizer, model, Prompts):
        self.tokenizer = tokenizer
        self.model = model
        self.prompt_embeddings = []

        for normal_prompt, class_prompt in Prompts:
            if self.tokenizer is not None:
                # no truncation here
                class_inputs = self.tokenizer(class_prompt, return_tensors="pt", truncation=False) 
                normal_inputs = self.tokenizer(normal_prompt, return_tensors="pt", truncation=False)
            else:
                class_inputs = class_prompt
                normal_inputs = normal_prompt
            
            with torch.no_grad():
                if not isinstance(class_inputs, str):
                    CR = self.model(**class_inputs)
                    NR = self.model(**normal_inputs)

                    if "last_hidden_state" in CR and "last_hidden_state" in NR:
                        class_embedding = CR.last_hidden_state.mean(dim=1).squeeze().numpy()
                        normal_embedding = NR.last_hidden_state.mean(dim=1).squeeze().numpy()
                    elif "logits" in CR and "logits" in NR:
                        class_embedding = CR.logits.mean(dim=1).squeeze().numpy()
                        normal_embedding = NR.logits.mean(dim=1).squeeze().numpy()
                    else:
                        print("CR keys:", CR.keys())
                        raise ValueError("Unsupported model output format for zero-shot embedding extraction")
                else:
                    class_embedding = self.model.transform([class_prompt])[0]
                    normal_embedding = self.model.transform([normal_prompt])[0]
            
            self.prompt_embeddings.append((normal_embedding, class_embedding))
        
    def fit(self, X, Y):
        return # no fitting needed for zero-shot

    def predict(self, X):
        if sp.issparse(X):
            X = X.toarray()
        X = np.asarray(X)
        # X is an encoded text embedding, we will compare it with the prompt embeddings using cosine similarity
        predictions = []
        for x in X:
            sample_preds = []
            for normal_emb, class_emb in self.prompt_embeddings:
                sim_normal = np.dot(x, normal_emb) / (np.linalg.norm(x) * np.linalg.norm(normal_emb) + 1e-8)
                sim_class  = np.dot(x, class_emb) / (np.linalg.norm(x) * np.linalg.norm(class_emb) + 1e-8)
                # if the embedding is closer to the class prompt than the normal prompt, we predict 1, else 0
                sim_score_class = np.sum(sim_class)
                sim_score_normal = np.sum(sim_normal)
                pred = 1 if sim_score_class > sim_score_normal else 0
                sample_preds.append(pred)
            predictions.append(sample_preds)
        return np.array(predictions)
    
def get_zero_shot_models(name : str, tokenizer, model):
    return [
        (f"Zero-Shot {name} Descriptive Sentences", ZeroShotModel_promptBased(tokenizer, model, Prompts_Descriptive_Sentences)),
        (f"Zero-Shot {name} Single Words", ZeroShotModel_promptBased(tokenizer, model, Prompts_Single_Word)),
        (f"Zero-Shot {name} Word Sets", ZeroShotModel_promptBased(tokenizer, model, Prompts_Wordset)),
    ]

In [50]:
# train the distance based zero-shot model
zero_shot_distance_model = ZeroShotModel_projectionBased()

# gpt2
train_and_test(
    models=[
        ("Zero-Shot (Projection based)", zero_shot_distance_model),
    ],
    encoders=[
        ("GPT-2", None), # pass None since we are pre-encoding the data, and predictor will use the pre-encoded data directly
    ],
    quiet=True,
    X_train_encoded={"GPT-2": np.vstack(encoded_train_gpt2)}, # pass pre-encoded data to skip encoding again
    X_test_encoded={"GPT-2": np.vstack(encoded_test_gpt2)}, # pass pre-encoded data to skip encoding again
    forced_train_df = gpt2_train_df, # use the new smaller train set
    forced_test_df = gpt2_test_df, # use the new smaller test set
)

# bert
train_and_test(
    models=[
        ("Zero-shot (Projection based)", zero_shot_distance_model),
    ],
    encoders=[
        ("BERT", None), 
    ],
    quiet=True,
    X_train_encoded={"BERT": bert_train_encodings}, # pass pre-encoded data to skip encoding again
    X_test_encoded={"BERT": bert_test_encodings}, # pass pre-encoded data to skip encoding again
    forced_train_df=bert_train_df,
    forced_test_df=bert_test_df,
)

# word2vec
train_and_test(
    models=[
        ("Zero-shot (Projection based)", zero_shot_distance_model),
    ],
    encoders=[
        ("Word2Vec", word2vec_encoder),
    ],
    quiet=True,
)

Training model Zero-Shot (Projection based)
Evaluated Zero-Shot (Projection based) in 0.06s
Training model Zero-shot (Projection based)
Evaluated Zero-shot (Projection based) in 0.02s
Encoded X_train with 1 encoders in 1.16s, averaged 1.16s / encoder
Training model Zero-shot (Projection based)
Evaluated Zero-shot (Projection based) in 11.86s

In [51]:
train_and_test(
    models=get_zero_shot_models("GPT-2", tokenizer_gpt2, model_gpt2),
    encoders=[
        ("GPT-2", None), # pass None since we are pre-encoding the data, and predictor will use the pre-encoded data directly
    ],
    quiet=True,
    X_train_encoded={"GPT-2": np.vstack(encoded_train_gpt2)}, # pass pre-encoded data to skip encoding again
    X_test_encoded={"GPT-2": np.vstack(encoded_test_gpt2)}, # pass pre-encoded data to skip encoding again
    forced_train_df = bert_train_df, # use the new smaller train set
    forced_test_df = bert_test_df, # use the new smaller test set
)

Training model Zero-Shot GPT-2 Descriptive Sentences
Evaluated Zero-Shot GPT-2 Descriptive Sentences in 0.13s
Training model Zero-Shot GPT-2 Single Words
Evaluated Zero-Shot GPT-2 Single Words in 0.14s
Training model Zero-Shot GPT-2 Word Sets
Evaluated Zero-Shot GPT-2 Word Sets in 0.13s

In [52]:
train_and_test(
    models=get_zero_shot_models("Word2Vec", None, word2vec_encoder),
    encoders=[
        ("Word2Vec", word2vec_encoder),
    ],
    quiet=True,
)

Encoded X_train with 1 encoders in 0.85s, averaged 0.85s / encoder
Training model Zero-Shot Word2Vec Descriptive Sentences
Evaluated Zero-Shot Word2Vec Descriptive Sentences in 18.22s
Training model Zero-Shot Word2Vec Single Words
Evaluated Zero-Shot Word2Vec Single Words in 18.16s
Training model Zero-Shot Word2Vec Word Sets
Evaluated Zero-Shot Word2Vec Word Sets in 18.14s

In [53]:
train_and_test(
    models=get_zero_shot_models("Distilled BERT", bert_tokenizer, bert_model),
    encoders=[
        ("BERT", None), # pass None since we are pre-encoding the data, and predictor will use the pre-encoded data directly
    ],
    quiet=True,
    X_train_encoded={"BERT": bert_train_encodings}, # pass pre-encoded data to skip encoding again
    X_test_encoded={"BERT": bert_test_encodings}, # pass pre-encoded data to skip encoding again
    forced_test_df=bert_test_df, # use the new smaller test set
    forced_train_df=bert_train_df, # use the new smaller train set
)

Training model Zero-Shot Distilled BERT Descriptive Sentences
Evaluated Zero-Shot Distilled BERT Descriptive Sentences in 0.07s
Training model Zero-Shot Distilled BERT Single Words
Evaluated Zero-Shot Distilled BERT Single Words in 0.07s
Training model Zero-Shot Distilled BERT Word Sets
Evaluated Zero-Shot Distilled BERT Word Sets in 0.07s

In [54]:
# remove duplicated model (if any)
score_df = score_df.drop_duplicates(subset=["model"])
display(score_df.sort_values(by="f1-score", ascending=False))
# csv
print(score_df.sort_values(by="f1-score", ascending=False).to_csv(index=False))

,model,accuracy,precision,recall,f1-score
65,RNN Depth 2 (GPT-2 + PCA),0.440000,0.799901,0.933173,0.854641
67,Zero-Shot (Projection based) (GPT-2),0.467000,0.786295,0.945765,0.851141
66,RNN Depth 3 (GPT-2 + PCA),0.620000,0.806526,0.910566,0.850865
24,NN Depth 2 (BOW),0.724470,0.883141,0.799078,0.836758
6,Decision Tree (BOW),0.659813,0.847433,0.799340,0.821739
...,...,...,...,...,...
40,RNN Depth 3 (Word2Vec),0.445648,0.000000,0.000000,0.000000
17,RNN Depth 2 (TF-IDF),0.445648,0.000000,0.000000,0.000000
33,RNN Depth 2 (Distilled BERT),0.422000,0.000000,0.000000,0.000000
19,RNN Depth 3 (TF-IDF),0.445648,0.000000,0.000000,0.000000
27,Linear_a (Distilled BERT),0.422000,0.000000,0.000000,0.000000

model,accuracy,precision,recall,f1-score
RNN Depth 2 (GPT-2 + PCA),0.44,0.7999013207384144,0.9331725800895625,0.8546412875479031
Zero-Shot (Projection based) (GPT-2),0.467,0.786295019097156,0.9457649815868765,0.8511410778184496
RNN Depth 3 (GPT-2 + PCA),0.62,0.8065255258775174,0.9105658884052236,0.8508648354594879
NN Depth 2 (BOW),0.7244695807770961,0.8831405575921787,0.7990781021997354,0.8367583307141945
Decision Tree (BOW),0.6598127556237219,0.8474329443906412,0.7993396019553973,0.8217386754310149
NN Depth 3 (BOW),0.6949610173824131,0.8575339172200501,0.7894829668018831,0.8201604963568697
NN Depth 3 (TF-IDF),0.718558282208589,0.8624830940836292,0.7860833321272993,0.8182476715589864
Decision Tree (TF-IDF),0.6241053169734151,0.8245701962983897,0.79032237207919,0.8058081098647131
NN Depth 2 (TF-IDF),0.7554479805725971,0.9207366215117087,0.7363983036917716,0.8043442361618025
Linear (BOW),0.7054895194274029,0.9155922271137465,0.7206698032377832,0.802424783077067
Random Forest (BOW),0.7416442995910021,0.9171535622414745,0.7259089066090012,0.7983378136773749
RNN Depth 1 (GPT-2 + PCA),0.405,0.6650908610955761,0.954382183908046,0.7692747480817781
SVM (TF-IDF),0.7630527862985685,0.9575188789737773,0.6791002277904328,0.7682987103634582
Random Forest (TF-IDF),0.7299495143149284,0.932414220203399,0.6788516813909609,0.7676338124460428
Zero-shot (Projection based) (BERT),0.42,0.6637433355390492,0.9418416801292407,0.7650806394838706
Zero-Shot Word2Vec Descriptive Sentences (Word2Vec),0.5367139570552147,0.6356134309870972,0.973807415480326,0.7649012163181859
NN Depth 2 (GPT-2 + PCA),0.313,0.6781037440979414,0.9033982436044292,0.7516633516063832
Decision Tree (GPT-2),0.491,0.7788792854508433,0.7349397590361446,0.7497207174776146
Linear (TF-IDF),0.7416602760736196,0.9546182611438397,0.6555753510794383,0.7456876135050187
Zero-shot (Projection based) (Word2Vec),0.4325153374233129,0.6323707288351823,0.9482798015406712,0.7444616793166209
Decision Tree (TF-IDF + PCA),0.5088669478527608,0.7519729776305452,0.7292759043299177,0.7394756616045163
Decision Tree (BOW + PCA),0.4894075920245399,0.7494514484565352,0.7305631466520282,0.7389310252540072
Zero-Shot GPT-2 Word Sets (GPT-2),0.452,0.605781774034827,0.9536144578313253,0.734656642090865
Zero-Shot GPT-2 Single Words (GPT-2),0.45,0.5942586877002107,0.9820065430752454,0.734323688494653
Zero-Shot Word2Vec Word Sets (Word2Vec),0.4580457566462168,0.5858908205696013,0.99963155826292,0.7316982663507623
RNN Depth 1 (GPT-2),0.432,0.6300426173052087,0.9220835126990959,0.7315264996727543
NN Depth 1 (Distilled BERT),0.314,0.6090851189922841,0.9243515850144092,0.7301880274962527
All One Predictor,0.4495782208588957,0.5830411912663727,1.0,0.7293070902326496
Linear (GPT-2 + PCA),0.594,0.8452348834887705,0.6448430493273543,0.7255930219894051
NN Depth 1 (GPT-2 + PCA),0.156,0.6716535899292012,0.8212835093419983,0.7255853066829309
Zero-Shot GPT-2 Descriptive Sentences (GPT-2),0.42,0.6869360138181984,0.8162100456621004,0.723383796637401
Linear (GPT-2),0.584,0.8129718872815787,0.6536118363794604,0.7210826117467819
NN Depth 1 (BOW),0.7175198108384458,0.9481791258539859,0.6104717545354043,0.7142778287985978
NN Depth 3 (Distilled BERT),0.332,0.5658065025252527,0.9375,0.7016419767973772
Decision Tree (Word2Vec + PCA),0.42059688139059304,0.6784264725010852,0.7282896998870279,0.70083090307689
Decision Tree (Word2Vec),0.41765720858895705,0.6738058524491669,0.7329985756705212,0.7001577562577388
Linear (TF-IDF + PCA),0.7068475204498977,0.9268895674905949,0.5939628593962859,0.6860676804370994
Random Predictor,0.2363401073619632,0.5845949568839682,0.8587189186533697,0.6854288171377143
SVM (BOW),0.729693890593047,0.9557650552436209,0.6076709879302638,0.6732010566758586
Decision Tree (GPT-2 + PCA),0.418,0.7190911492673826,0.6377952755905512,0.6717584966898291
Decision Tree (Distilled BERT),0.394,0.6708447475982742,0.666083916083916,0.6654544777470104
Zero-Shot Word2Vec Single Words (Word2Vec),0.24870590490797545,0.5200839859425833,0.8941274099233842,0.6519264089661301
NN Depth 3 (Word2Vec + PCA),0.6655483128834356,0.6558890114271498,0.6385621334017116,0.6458849387371942
NN Depth 2 (Word2Vec + PCA),0.6402735173824131,0.6426798507888424,0.5940516348819345,0.6152453248895539
NN Depth 3 (Word2Vec),0.6292976738241309,0.6425772226780337,0.5854174650515688,0.6095927322307392
Linear (BOW + PCA),0.6707087167689162,0.9631589627819895,0.49992265748868864,0.6046295178175003
Zero-Shot Distilled BERT Descriptive Sentences (BERT),0.198,0.5518165823949599,0.7108433734939759,0.5979153375076803
NN Depth 2 (Word2Vec),0.6115158486707567,0.6363182038136614,0.5739448988809154,0.5964105030231491
NN Depth 2 (Distilled BERT),0.128,0.49421748878923766,0.7387892376681614,0.5901639071170139
Zero-Shot Distilled BERT Single Words (BERT),0.156,0.5447413613150496,0.7046818727490997,0.5895740143672318
Linear (Word2Vec + PCA),0.6102217535787321,0.720213044762437,0.5552625228393147,0.5848201973218696
Linear (Word2Vec),0.6066749744376279,0.7297060924954947,0.5492909028017987,0.5807920335301597
NN Depth 1 (Word2Vec + PCA),0.5973287321063395,0.6553682488124033,0.5359941234084231,0.5651672764217812
Zero-Shot Distilled BERT Word Sets (BERT),0.414,0.5458942014536102,0.6333333333333333,0.5642616957894325
RNN Depth 1 (Word2Vec + PCA),0.1343941717791411,0.5849365278845435,0.6600861862081199,0.5640547230762778
RNN Depth 3 (Distilled BERT),0.402,0.48718861209964415,0.6583629893238434,0.5599869104593611
NN Depth 1 (GPT-2),0.014,0.46758372475193766,0.7541686517389233,0.5504348029016941
RNN Depth 2 (Word2Vec + PCA),0.4816589979550102,0.6225549804231456,0.584764317662882,0.5464476193297497
RNN Depth 1 (TF-IDF),0.3974948875255624,0.49934699557670265,0.6224525090969465,0.531358528552161
RNN Depth 1 (BOW),0.47065120143149286,0.7072735947224443,0.5705422547107514,0.510066444414845
NN Depth 3 (GPT-2 + PCA),0.24,0.7839135383384142,0.5040387722132472,0.46654800779799643
RNN Depth 2 (BOW),0.581064672801636,0.6453697504752155,0.45325726218443524,0.44839836684385553
NN Depth 1 (TF-IDF),0.6032080777096115,0.6654203525644727,0.4054733259458604,0.4430437328759654
RNN Depth 2 (GPT-2),0.331,0.6105580455527881,0.3849056603773585,0.4231641834560042
RNN Depth 3 (BOW),0.5783806237218814,0.9503979318028737,0.3937325959916853,0.41512354178274513
RNN Depth 3 (Word2Vec + PCA),0.5214404396728016,0.50517492054961,0.4107940937977333,0.4072625349687895
NN Depth 2 (GPT-2),0.543,0.5712181671581004,0.3823178016726404,0.40587286403437084
NN Depth 1 (Word2Vec),0.5127492331288344,0.5882583043168608,0.30704202232435984,0.3906148279161789
RNN Depth 1 (Distilled BERT),0.18,0.28304680851063835,0.5425531914893617,0.36751058186127883
RNN Depth 3 (GPT-2),0.461,0.33507218587863746,0.0747800586510264,0.12227195554869578
RNN Depth 1 (Word2Vec),0.4345922801635992,0.07774120094235701,0.013647127755670027,0.023071873561447014
NN Depth 3 (GPT-2),0.427,0.28358526719182453,0.00894187779433681,0.01733709057067923
RNN Depth 2 (Word2Vec),0.4330265848670757,0.01948949840534944,0.0029429949301347847,0.005113786875138306
All Zero Predictor,0.4456480061349693,0.0,0.0,0.0
RNN Depth 3 (Word2Vec),0.4456480061349693,0.0,0.0,0.0
RNN Depth 2 (TF-IDF),0.4456480061349693,0.0,0.0,0.0
RNN Depth 2 (Distilled BERT),0.422,0.0,0.0,0.0
RNN Depth 3 (TF-IDF),0.4456480061349693,0.0,0.0,0.0
Linear_a (Distilled BERT),0.422,0.0,0.0,0.0