# Depressive and Suicidal text classification

**Datasets used:**
1. [Classified Twitter posts](https://www.kaggle.com/datasets/munkialbright/classified-tweets)
2. [Derived dataset from Murarka et al., Nikhileswar Komati and Suchintika Sarkar](https://www.kaggle.com/datasets/priyangshumukherjee/mental-health-text-classification-dataset)

## Imports

In [1]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import random

## Download the dataset

In [2]:
import kagglehub

In [3]:
path1 = kagglehub.dataset_download("munkialbright/classified-tweets")
print("Path to dataset 1:", path1)

Using Colab cache for faster access to the 'classified-tweets' dataset.
Path to dataset 1: /kaggle/input/classified-tweets

In [4]:
path2 = kagglehub.dataset_download("priyangshumukherjee/mental-health-text-classification-dataset")
print("Path to dataset 2:", path2)

Using Colab cache for faster access to the 'mental-health-text-classification-dataset' dataset.
Path to dataset 2: /kaggle/input/mental-health-text-classification-dataset

## Seed the randoms

In [5]:
SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)
random.seed(SEED)

## Set up dataframes

In [6]:
# We do multi-label (binary label) classification
# with possible missing values in the labels
# 0 = not present, 1 = present, -1 = unknown/missing
# normal text have all labels = 0

df_all = pd.DataFrame(columns=["text", "isSuspicious", "isRacist", "isSexist", "isHate", "isDepressive", "isSuicidal", "isAnxiety"])

In [7]:
df_all1 = pd.read_csv(path1 + "/classified_tweets.csv")
# print columns
print("Columns in dataset 1:", df_all1.columns)

# cols =
# 'text' -> text of the tweet
# 'suspicious' -> 0 or 1 if the tweet is suspicious (contains harmful content)
# 'cyberbullying' -> 0 if nothing, 1 if racist, 2 if sexist
# 'hate' -> 0 or 1 if the tweet contains hate speech
# 'suicidal' -> 0 or 1 if the tweet contains suicidal content

# this dataset has no depressive / anxiety labels, so we will fill them with -1 (unknown/missing)
df_all1["isDepressive"] = -1
df_all1["isAnxiety"] = -1
# rename columns to match our format
df_all1.rename(columns={
    "suspicious": "isSuspicious",
    "hate": "isHate",
    "suicidal": "isSuicidal"
}, inplace=True)

# convert cyberbullying to isRacist and isSexist
df_all1["isRacist"] = df_all1["cyberbullying"].apply(lambda x: 1 if x == 1 else 0)
df_all1["isSexist"] = df_all1["cyberbullying"].apply(lambda x: 1 if x == 2 else 0)
# drop the original cyberbullying column
df_all1.drop(columns=["cyberbullying"], inplace=True)

display(df_all1.head())

df_all = pd.concat([df_all, df_all1], ignore_index=True)

Columns in dataset 1: Index(['text', 'suspicious', 'cyberbullying', 'hate', 'suicidal'], dtype='object')

,text,isSuspicious,isHate,isSuicidal,isDepressive,isAnxiety,isRacist,isSexist
0,Uhmm like 6th grade on a corner of a street....,0,0,0,-1,-1,0,0
1,a) JTP is a douchebag b) Stewart kicks ass!,1,0,0,-1,-1,0,0
2,ditto bitch!,1,0,0,-1,-1,0,0
3,damn I have to drive my dad to the airport tha...,0,0,0,-1,-1,0,0
4,:],0,0,0,-1,-1,0,0

In [8]:
df_all2 = pd.read_csv(path2 + "/mental_heath_unbanlanced.csv")

# print columns
print("Columns in dataset 2:", df_all2.columns)

# cols =
# 'text' -> text of the post
# 'status' -> the text Normal, Depression, Suicidal, Anxiety

def getRow(
        default_num : int,
        change_key : str = None,
        change_value : int = None
    ):
    res = {
        "isSuspicious": default_num,
        "isRacist": default_num,
        "isSexist": default_num,
        "isHate": default_num,
        "isDepressive": default_num,
        "isSuicidal": default_num,
        "isAnxiety": default_num,
    }
    if change_key is not None and change_value is not None:
        res[change_key] = change_value
    return res

mapping_cols = {
    "Normal"     : getRow(0),
    "Depression" : getRow(-1, "isDepressive", 1),
    "Suicidal"   : getRow(-1, "isSuicidal", 1),
    "Anxiety"    : getRow(-1, "isAnxiety", 1),
}

# apply the mapping to the status column and create new columns
for status, mapping in mapping_cols.items():
    df_all2.loc[df_all2["status"] == status, ["isSuspicious", "isRacist", "isSexist", "isHate", "isDepressive", "isSuicidal", "isAnxiety"]] = mapping.values()

# drop the original status column
df_all2.drop(columns=["status", "Unique_ID"], inplace=True)

display(df_all2.head())

df_all = pd.concat([df_all, df_all2], ignore_index=True)

Columns in dataset 2: Index(['Unique_ID', 'text', 'status'], dtype='object')

,text,isSuspicious,isRacist,isSexist,isHate,isDepressive,isSuicidal,isAnxiety
0,oh my gosh,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0
1,"trouble sleeping, confused mind, restless hear...",-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0
2,"All wrong, back off dear, forward doubt. Stay ...",-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0
3,I've shifted my focus to something else but I'...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0
4,"I'm restless and restless, it's been a month n...",-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0

In [9]:
del df_all1
del df_all2

In [10]:
# turn any value > 1 in whatever col into 1
for col in ["isSuspicious", "isRacist", "isSexist", "isHate", "isDepressive", "isSuicidal", "isAnxiety"]:
    df_all[col] = df_all[col].apply(lambda x: 1 if x > 1 else x)

## Print stat

In [11]:
num_samples = len(df_all)
print("Total number of samples:", num_samples)

Total number of samples: 69546

In [12]:
count_df = df_all[["isSuspicious", "isRacist", "isSexist", "isHate", "isDepressive", "isSuicidal", "isAnxiety"]].apply(pd.Series.value_counts).T
print("Label distribution:")
print(count_df)

Label distribution:
               -1.0    0.0    1.0
isSuspicious  31221  31110   7215
isRacist      31221  37380    945
isSexist      31221  36592   1733
isHate        31221  35647   2678
isDepressive  36649  18391  14506
isSuicidal    20009  37277  12260
isAnxiety     45652  18391   5503

## Helpers

In [13]:
from sklearn.model_selection import train_test_split
# split into train and test sets

# models bahaved rlly well, reduced train size to 20% to see if it can generalize better
# new note, NN at 20% still have liek 99% accuracy, reduced to 10% to intentionally handicap it
train_df, test_df = train_test_split(df_all, test_size=0.9, random_state=42)

In [14]:
score_df = pd.DataFrame(columns=["model", "accuracy", "precision", "recall", "f1-score"])

In [15]:
from sklearn.metrics import classification_report, multilabel_confusion_matrix, accuracy_score, f1_score, precision_score, recall_score

def evaluate(
    model_name : str,
    preditor, # function from tensor of features (X) to list of predicted labels
    encoder, # function from list of texts to tensor of features (X)
    quiet : bool = False,

    X_test_encoded = None, # optional pre-encoded features for the test set, if already computed outside to save time
    df = test_df, # optional dataframe to use instead of the global test_df
):
    X = X_test_encoded if X_test_encoded is not None else encoder(df["text"].tolist()) 
    y_true = df[["isSuspicious", "isRacist", "isSexist", "isHate", "isDepressive", "isSuicidal", "isAnxiety"]].values
    y_pred = preditor(X)
    if len(y_pred) != len(y_true):
        # clamp both to the min
        min_len = min(len(y_pred), len(y_true))
        y_pred = y_pred[:min_len]
        y_true = y_true[:min_len]
    # For missing labels (-1), consider any prediction as correct
    missing_mask = y_true == -1
    y_true = y_true.astype(float)
    y_true[missing_mask] = y_pred[missing_mask]
    y_true = y_true.astype(int)
    # print classification report for each label
    # print multilabel confusion matrix for each label
    # print(multilabel_confusion_matrix(y_true, y_pred))
    # print overall accuracy, f1 score, precision, recall
    accuracy = accuracy_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred, average="weighted")
    precision = precision_score(y_true, y_pred, average="weighted")
    recall = recall_score(y_true, y_pred, average="weighted")
    score_df.loc[len(score_df)] = [model_name, accuracy, precision, recall, f1] # add to score_df

    if quiet:
        return

    print(classification_report(y_true, y_pred, target_names=["isSuspicious", "isRacist", "isSexist", "isHate", "isDepressive", "isSuicidal", "isAnxiety"]))
    print("Overall accuracy:", accuracy)
    print("Overall f1 score:", f1)
    print("Overall precision:", precision)
    print("Overall recall:", recall)

In [16]:
import time
def fit_encoders(
    encoders, # list of encoders with fit methods
):
    time_start = time.time()
    for encoder in encoders:
        encoder.fit(train_df["text"].tolist())
    time_end = time.time()
    print(f"Encoders fit time: {time_end - time_start:.2f}s, averaged {(time_end - time_start) / len(encoders):.2f}s / encoder")

In [17]:
ATTR_NAMES = ["isSuspicious", "isRacist", "isSexist", "isHate", "isDepressive", "isSuicidal", "isAnxiety"]

def random_missing_handler(Y):
    """Assign missing labels (-1) randomly to 0 or 1."""
    Y[Y == -1] = np.random.randint(0, 2, size=(Y == -1).sum())

def class_distribution_missing_handler(Y, bias_pos=0, bias_neg=15):
    """
    Assign missing labels based on observed class distribution for each label.
    bias_pos/bias_neg: optional bias toward positive/negative classes.
    """
    for col_idx in range(Y.shape[1]):
        col = Y[:, col_idx]
        known_mask = col != -1
        if known_mask.sum() > 0:
            # Calculate class distribution from known labels
            sum_pos = (col[known_mask] == 1).sum() + bias_pos
            sum_neg = (col[known_mask] == 0).sum() + bias_neg
            total = sum_pos + sum_neg
            if total > 0:
                p_pos = sum_pos / total
                p_neg = sum_neg / total
                missing_count = (col == -1).sum()
                if missing_count > 0:
                    Y[col == -1, col_idx] = np.random.choice([0, 1], size=missing_count, p=[p_neg, p_pos])
            else:
                # Fallback: random with equal probability
                missing_count = (col == -1).sum()
                if missing_count > 0:
                    Y[col == -1, col_idx] = np.random.choice([0, 1], size=missing_count, p=[0.5, 0.5])

def train_and_test(
    models, # list of (model_name, model (with predict method)),
    encoders, # list of (encoder_name, encoder models with at least transform (str -> tensor) as a method, assumed fitted already
    quiet : bool = False,

    # missing_handler(Y_train) modifies Y_train in place
    missing_handler = class_distribution_missing_handler,
    
    # Optional pre-encoded data to skip encoding
    X_train_encoded : dict = None,
    X_test_encoded : dict = None,

    forced_train_df = train_df, # optional dataframe to use instead of the global train_df
    forced_test_df = test_df, # optional dataframe to use instead of the global test_df
):
    train_df = forced_train_df
    test_df = forced_test_df
    # fit
    encoded = None # map from encoder_name to encoded X_train
    skip_precompute_encodings = X_train_encoded is not None
    if not skip_precompute_encodings:
        encoded = {}
        time_start = time.time()
        for encoder_name, encoder in encoders:
            encoded[encoder_name] = encoder.transform(train_df["text"].tolist())
        time_end = time.time()
        print(f"Encoded X_train with {len(encoders)} encoders in {time_end - time_start:.2f}s, averaged {(time_end - time_start) / len(encoders):.2f}s / encoder")
    else:
        # Use pre-encoded data if provided
        encoded = X_train_encoded

    # Process Y_train with missing_handler
    Y_train = train_df[ATTR_NAMES].values
    missing_handler(Y_train)

    for model_name, model in models:
        print(f"Training model {model_name}")

        time_start = time.time()
        for encoder_name, encoder in encoders:
            if skip_precompute_encodings:
                if X_train_encoded is not None:
                    X_train = X_train_encoded[encoder_name]
                else:
                    X_train = encoder.transform(train_df["text"].tolist())
            else:
                X_train = encoded[encoder_name]

            model.fit(X_train, Y_train) # fit the model on the encoded X_train and Y_train

            def predictor(X):
                if X_test_encoded is not None and encoder_name in X_test_encoded:
                    return model.predict(X_test_encoded[encoder_name])
                else:
                    X_encoded = encoder.transform(X) if isinstance(X, list) else X
                    return model.predict(X_encoded)
            evaluate(f"{model_name} ({encoder_name})", predictor, lambda texts: texts, quiet=quiet, df=test_df)

        time_end = time.time()
        print(f"Evaluated {model_name} in {time_end - time_start:.2f}s")
        del model

## Dummy model

In [18]:
def random_predictor(X):
    if isinstance(X, torch.Tensor):
        X = X.cpu().numpy()
        num_samples = X.shape[0]
    else:
        if isinstance(X, list):
            num_samples = len(X)
    num_labels = 7
    return np.random.randint(2, size=(num_samples, num_labels))

evaluate("Random Predictor", random_predictor, lambda texts: texts, quiet=False)

              precision    recall  f1-score   support

isSuspicious       0.55      0.84      0.67     20601
    isRacist       0.46      0.97      0.62     14660
    isSexist       0.47      0.95      0.63     15591
      isHate       0.49      0.93      0.64     16678
isDepressive       0.73      0.78      0.76     29476
  isSuicidal       0.46      0.72      0.57     20114
   isAnxiety       0.74      0.90      0.81     25369

   micro avg       0.56      0.86      0.68    142489
   macro avg       0.56      0.87      0.67    142489
weighted avg       0.58      0.86      0.69    142489
 samples avg       0.55      0.59      0.54    142489

Overall accuracy: 0.2363401073619632
Overall f1 score: 0.6854288171377143
Overall precision: 0.5845949568839682
Overall recall: 0.8587189186533697

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in samples with no true nor predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

## Classic models

This section will uses traditional encoders (TF-IDF and BOW) with Traditional models (Logistic regression and Decision tree)

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.multioutput import MultiOutputClassifier

In [20]:
N_FEAT = 5000

vectorizer_tfidf = TfidfVectorizer(max_features=N_FEAT)
vectorizer_BOW = CountVectorizer(max_features=N_FEAT)

print("Fitting encoders...")
fit_encoders([vectorizer_tfidf, vectorizer_BOW])

model_linear = MultiOutputClassifier(LogisticRegression(max_iter=1000))
model_decision_tree = MultiOutputClassifier(DecisionTreeClassifier())

# these 2 takes way too long for not a notable improvement, so we will ignore them for now
# model_random_forest = MultiOutputClassifier(RandomForestClassifier())
# model_svm = MultiOutputClassifier(SVC())

train_and_test(
    models=[
        ("Linear", model_linear),
        ("Decision Tree", model_decision_tree),
        # ("Random Forest", model_random_forest),
        # ("SVM", model_svm),
    ],
    encoders=[
        ("TF-IDF", vectorizer_tfidf),
        ("BOW", vectorizer_BOW),
    ],
    quiet=True
)

Fitting encoders...
Encoders fit time: 0.56s, averaged 0.28s / encoder
Encoded X_train with 2 encoders in 0.51s, averaged 0.26s / encoder
Training model Linear
Evaluated Linear in 9.63s
Training model Decision Tree
Evaluated Decision Tree in 50.44s

In [21]:
display(score_df.sort_values(by="f1-score", ascending=False))

                    model  accuracy  precision    recall  f1-score
4     Decision Tree (BOW)  0.655771   0.848781  0.800572  0.822721
3  Decision Tree (TF-IDF)  0.626534   0.823943  0.791150  0.806205
2            Linear (BOW)  0.698620   0.912369  0.714989  0.798001
1         Linear (TF-IDF)  0.736580   0.952171  0.646942  0.739849
0        Random Predictor  0.236340   0.584595  0.858719  0.685429

## Recurrent Neural Net

In [24]:
import scipy.sparse as sp
def make_rnn_model(depth : int, in_dim, out_dim = 7, hidden_dim = 128, batch_size = 32, epochs = 5, lr = 0.001):    
    class SimpleRNN(nn.Module):
        def __init__(self):
            super(SimpleRNN, self).__init__()
            self.hidden_size = hidden_dim
            self.rnn_arr = nn.ModuleList([
                nn.RNN(in_dim if i == 0 else hidden_dim, hidden_dim, batch_first=True) for i in range(depth)
            ])
            self.fc = nn.Linear(hidden_dim, out_dim)
            self.epochs = epochs
            self.batch_size = batch_size
            self.lr = lr

        def fit(self, X, Y):
            # Convert sparse matrices to dense
            if sp.issparse(X):
                X = X.toarray()
            X = np.asarray(X)
            Y = np.asarray(Y)
            
            X_t = torch.tensor(X, dtype=torch.float32)
            Y_t = torch.tensor(Y, dtype=torch.float32)
            
            # Add sequence dimension: (batch_size, features) -> (batch_size, 1, features)
            if X_t.dim() == 2:
                X_t = X_t.unsqueeze(1)
            
            self.train()
            optimizer = torch.optim.Adam(self.parameters(), lr=self.lr)
            criterion = nn.BCEWithLogitsLoss()
            for epoch in range(self.epochs):
                optimizer.zero_grad()
                outputs = self.forward(X_t)
                loss = criterion(outputs, Y_t)
                loss.backward()
                optimizer.step()

        def predict(self, X):
            # Convert sparse matrices to dense
            if sp.issparse(X):
                X = X.toarray()
            X = np.asarray(X)
            
            X_t = torch.tensor(X, dtype=torch.float32)
            
            # Add sequence dimension
            if X_t.dim() == 2:
                X_t = X_t.unsqueeze(1)
            
            self.eval()
            with torch.no_grad():
                outputs = self.forward(X_t)
                return (torch.sigmoid(outputs) > 0.5).int().numpy()

        def forward(self, x):
            # x should be a tensor of shape (batch_size, seq_len, features)
            h = None
            for rnn in self.rnn_arr:
                x, h = rnn(x, h)
            # take the last output of the sequence
            x = x[:, -1, :]
            x = self.fc(x)
            return x

    return SimpleRNN()

In [25]:
rnn_model_d1 = make_rnn_model(depth=1, in_dim=N_FEAT)
rnn_model_d2 = make_rnn_model(depth=2, in_dim=N_FEAT)
rnn_model_d3 = make_rnn_model(depth=3, in_dim=N_FEAT)

train_and_test(
    models=[
        ("RNN Depth 1", rnn_model_d1),
        ("RNN Depth 2", rnn_model_d2),
        ("RNN Depth 3", rnn_model_d3),
    ],
    encoders=[
        ("TF-IDF", vectorizer_tfidf),
        ("BOW", vectorizer_BOW),
    ],
    quiet=True
)

Encoded X_train with 2 encoders in 0.51s, averaged 0.25s / encoder
Training model RNN Depth 1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Evaluated RNN Depth 1 in 16.35s
Training model RNN Depth 2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Evaluated RNN Depth 2 in 15.23s
Training model RNN Depth 3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Evaluated RNN Depth 3 in 15.17s

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [26]:
display(score_df.sort_values(by="f1-score", ascending=False))

                     model  accuracy  precision    recall  f1-score
4      Decision Tree (BOW)  0.655771   0.848781  0.800572  0.822721
3   Decision Tree (TF-IDF)  0.626534   0.823943  0.791150  0.806205
2             Linear (BOW)  0.698620   0.912369  0.714989  0.798001
1          Linear (TF-IDF)  0.736580   0.952171  0.646942  0.739849
0         Random Predictor  0.236340   0.584595  0.858719  0.685429
6        RNN Depth 1 (BOW)  0.525882   0.682369  0.510036  0.508252
8        RNN Depth 2 (BOW)  0.590123   0.669825  0.464819  0.457066
5     RNN Depth 1 (TF-IDF)  0.056173   0.435816  0.412403  0.259336
10       RNN Depth 3 (BOW)  0.465219   0.536295  0.064753  0.108833
9     RNN Depth 3 (TF-IDF)  0.453381   0.315010  0.031790  0.057752
7     RNN Depth 2 (TF-IDF)  0.436094   0.062131  0.013463  0.022131

## Simple neural nets

In [27]:
import torch
from torch.utils.data import TensorDataset, DataLoader
import numpy as np
import scipy.sparse as sp

MAX_HIDDEN_SIZE = 128

# Wrapper to give a sklearn-like `fit`/`predict` interface to PyTorch models
def make_nn_model(depth : int, in_dim = N_FEAT, out_dim = 7, epochs=5, batch_size=32, lr=1e-3):
    class Wrapper:
        def __init__(self):
            layers = []
            last_dim = in_dim
            # build `depth` linear layers; ensure the final layer outputs `out_dim`
            for i in range(depth):
                if i == depth - 1:
                    new_out_dim = out_dim
                else:
                    # intermediate hidden size: half previous, but at least out_dim
                    new_out_dim = min(max(out_dim, last_dim // 2), MAX_HIDDEN_SIZE) # cap hidden size to prevent OOM and trains a bit faster
                print(f"Depth {depth} Layer {i}: {last_dim} -> {new_out_dim}")
                layers.append(nn.Linear(last_dim, new_out_dim))
                if i < depth - 1:
                    layers.append(nn.ReLU())
                else:
                    layers.append(nn.Sigmoid())
                last_dim = new_out_dim
            self.m = nn.Sequential(*layers)

        def fit(self, X, y):
            # handle scipy sparse matrices from vectorizers
            if sp.issparse(X):
                X = X.toarray()
            X = np.asarray(X)
            y = np.asarray(y)

            X_t = torch.tensor(X, dtype=torch.float32)
            y_t = torch.tensor(y, dtype=torch.float32)
            ds = TensorDataset(X_t, y_t)
            loader = DataLoader(ds, batch_size=batch_size, shuffle=True)
            opt = torch.optim.Adam(self.m.parameters(), lr=lr)
            loss_fn = torch.nn.BCELoss()
            self.m.train()
            for epoch in range(epochs):
                for xb, yb in loader:
                    opt.zero_grad()
                    out = self.m(xb)
                    loss = loss_fn(out, yb)
                    loss.backward()
                    opt.step()

        def predict(self, X):
            # handle scipy sparse matrices
            if sp.issparse(X):
                X = X.toarray()
            X = np.asarray(X)
            self.m.eval()
            with torch.no_grad():
                Xt = torch.tensor(X, dtype=torch.float32)
                out = self.m(Xt).numpy()
                return (out > 0.5).astype(int)

    return Wrapper()

# Create NN wrappers by depth
nn_model_depth1 = make_nn_model(depth=1)
nn_model_depth2 = make_nn_model(depth=2)
nn_model_depth3 = make_nn_model(depth=3)

models_to_use = [
    ("NN Depth 1", nn_model_depth1),
    ("NN Depth 2", nn_model_depth2),
    ("NN Depth 3", nn_model_depth3),
]

train_and_test(
    models=models_to_use,
    encoders=[
        ("TF-IDF", vectorizer_tfidf),
        ("BOW", vectorizer_BOW),
    ],
    quiet=True
)

# delete the NN models to free up GPU memory
del nn_model_depth1
del nn_model_depth2
del nn_model_depth3

Depth 1 Layer 0: 5000 -> 7
Depth 2 Layer 0: 5000 -> 128
Depth 2 Layer 1: 128 -> 7
Depth 3 Layer 0: 5000 -> 128
Depth 3 Layer 1: 128 -> 64
Depth 3 Layer 2: 64 -> 7
Encoded X_train with 2 encoders in 0.54s, averaged 0.27s / encoder
Training model NN Depth 1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Evaluated NN Depth 1 in 14.97s
Training model NN Depth 2
Evaluated NN Depth 2 in 28.52s
Training model NN Depth 3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Evaluated NN Depth 3 in 28.42s

In [28]:
NN_df = score_df
NN_df = NN_df.sort_values(by="f1-score", ascending=False)
display(NN_df)
# NN at depth 2 and 3 outperforms linear on TF-IDF but loses on BOW
# likely because BOW is more sparse and harder for NN to learn, while TF-IDF has more informative features that NN can leverag
# 2 is better than 3, likely due to 3 overfitting the small dataset, while 2 is a good balance of learning capacity and regularization

                     model  accuracy  precision    recall  f1-score
14        NN Depth 2 (BOW)  0.727697   0.885284  0.799566  0.837566
15     NN Depth 3 (TF-IDF)  0.744856   0.872350  0.808034  0.835309
16        NN Depth 3 (BOW)  0.701112   0.859137  0.806271  0.829920
4      Decision Tree (BOW)  0.655771   0.848781  0.800572  0.822721
13     NN Depth 2 (TF-IDF)  0.762078   0.926705  0.746710  0.813017
3   Decision Tree (TF-IDF)  0.626534   0.823943  0.791150  0.806205
2             Linear (BOW)  0.698620   0.912369  0.714989  0.798001
1          Linear (TF-IDF)  0.736580   0.952171  0.646942  0.739849
12        NN Depth 1 (BOW)  0.723958   0.949070  0.624361  0.722881
0         Random Predictor  0.236340   0.584595  0.858719  0.685429
6        RNN Depth 1 (BOW)  0.525882   0.682369  0.510036  0.508252
8        RNN Depth 2 (BOW)  0.590123   0.669825  0.464819  0.457066
11     NN Depth 1 (TF-IDF)  0.606020   0.666904  0.412344  0.448852
5     RNN Depth 1 (TF-IDF)  0.056173   0.435816  0.412403  0.259336
10       RNN Depth 3 (BOW)  0.465219   0.536295  0.064753  0.108833
9     RNN Depth 3 (TF-IDF)  0.453381   0.315010  0.031790  0.057752
7     RNN Depth 2 (TF-IDF)  0.436094   0.062131  0.013463  0.022131

## Sentence embedding as encoders

### BERT (Distilled)

In [29]:
!pip install --quiet --no-warn-script-location xformers trl
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# Load pre-trained BERT model and tokenizer
model_name = "distilbert-base-uncased"
bert_tokenizer = AutoTokenizer.from_pretrained(model_name)
bert_model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=7)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:122: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [30]:
# test
time_start = time.time()

text = "Hello, this is a test tweet to check if the BERT model can process it without errors."

class_inputs = bert_tokenizer([text], padding=True, truncation=True, return_tensors="pt")
outputs = bert_model(**class_inputs)
print("BERT output logits shape", outputs.logits.shape)
time_end = time.time()
print(f"Tested BERT in {time_end - time_start:.2f}s")

BERT output logits shape torch.Size([1, 7])
Tested BERT in 0.08s

In [31]:
def batch_encode_bert_single(texts, i, batch_size):
    batch_texts = texts[i:i+batch_size]
    inputs = bert_tokenizer(batch_texts, padding=True, truncation=True, return_tensors="pt")
    with torch.no_grad():
        outputs = bert_model(**inputs)
    return outputs.logits.cpu().numpy()

In [33]:
for bs in [8, 16, 32]:
    time_start = time.time()
    batch_encode_bert_single(test_df["text"].tolist(), 0, bs)
    time_end = time.time()
    print(f"BERT encoded 1 batch of size {bs} in {time_end - time_start:.2f}s, extrapolated to full test set: {(time_end - time_start) * (len(test_df) / bs):.2f}s")

BERT encoded 1 batch of size 8 in 0.55s, extrapolated to full test set: 4270.25s
BERT encoded 1 batch of size 16 in 3.50s, extrapolated to full test set: 13691.18s
BERT encoded 1 batch of size 32 in 7.88s, extrapolated to full test set: 15405.65s

In [34]:
# BERT is hella slow, even the distilled version

# we use 100 samples for train, 500 for test

FORCED_TRAIN_SIZE = 100
FORCED_TEST_SIZE = 500
bs = 8

new_train_indices = np.random.choice(train_df.index, size=FORCED_TRAIN_SIZE, replace=True)
new_test_indices = np.random.choice(test_df.index, size=FORCED_TEST_SIZE, replace=True)

bert_train_df = train_df.loc[new_train_indices].reset_index(drop=True)
bert_test_df = test_df.loc[new_test_indices].reset_index(drop=True)

# encode
bert_train_encodings = []
for i in range(0, FORCED_TRAIN_SIZE, bs):
    batch_encodings = batch_encode_bert_single(bert_train_df["text"].tolist(), i, bs)
    bert_train_encodings.append(batch_encodings)
    # progress print
    progress = min(i + bs, FORCED_TRAIN_SIZE) / FORCED_TRAIN_SIZE * 100
    print(f"Encoded {min(i + bs, FORCED_TRAIN_SIZE)} / {FORCED_TRAIN_SIZE} train samples ({progress:.2f}%)", end="\r")

print()
bert_train_encodings = np.vstack(bert_train_encodings)

bert_test_encodings = []
for i in range(0, FORCED_TEST_SIZE, bs):
    batch_encodings = batch_encode_bert_single(bert_test_df["text"].tolist(), i, bs)
    bert_test_encodings.append(batch_encodings)
    # progress print
    progress = min(i + bs, FORCED_TEST_SIZE) / FORCED_TEST_SIZE * 100
    print(f"Encoded {min(i + bs, FORCED_TEST_SIZE)} / {FORCED_TEST_SIZE} test samples ({progress:.2f}%)", end="\r")

print()
bert_test_encodings = np.vstack(bert_test_encodings)

Encoded 100 / 100 train samples (100.00%)
Encoded 500 / 500 test samples (100.00%)

In [35]:
EMBED_DIM = bert_train_encodings.shape[1]
print("BERT embedding dimension:", EMBED_DIM)

nn_model_bert1 = make_nn_model(depth=1, in_dim=EMBED_DIM)
nn_model_bert2 = make_nn_model(depth=2, in_dim=EMBED_DIM)
nn_model_bert3 = make_nn_model(depth=3, in_dim=EMBED_DIM)

rnn_model_bert1 = make_rnn_model(depth=1, in_dim=EMBED_DIM)
rnn_model_bert2 = make_rnn_model(depth=2, in_dim=EMBED_DIM)
rnn_model_bert3 = make_rnn_model(depth=3, in_dim=EMBED_DIM)

train_and_test(
    models=[
        ("Linear", model_linear),
        ("Decision Tree", model_decision_tree),
        ("NN Depth 1", nn_model_bert1),
        ("NN Depth 2", nn_model_bert2),
        ("NN Depth 3", nn_model_bert3),
        ("RNN Depth 1", rnn_model_bert1),
        ("RNN Depth 2", rnn_model_bert2),
        ("RNN Depth 3", rnn_model_bert3),
    ],
    encoders=[
        ("Distilled BERT", None), 
    ],
    quiet=True,
    X_train_encoded={"Distilled BERT": bert_train_encodings},
    X_test_encoded={"Distilled BERT": bert_test_encodings},
    forced_train_df=bert_train_df,
    forced_test_df=bert_test_df,
)

BERT embedding dimension: 7
Depth 1 Layer 0: 7 -> 7
Depth 2 Layer 0: 7 -> 7
Depth 2 Layer 1: 7 -> 7
Depth 3 Layer 0: 7 -> 7
Depth 3 Layer 1: 7 -> 7
Depth 3 Layer 2: 7 -> 7
Training model Linear

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Evaluated Linear in 0.21s
Training model Decision Tree
Evaluated Decision Tree in 0.07s
Training model NN Depth 1
Evaluated NN Depth 1 in 0.07s
Training model NN Depth 2
Evaluated NN Depth 2 in 0.05s
Training model NN Depth 3
Evaluated NN Depth 3 in 0.06s
Training model RNN Depth 1
Evaluated RNN Depth 1 in 0.03s
Training model RNN Depth 2
Evaluated RNN Depth 2 in 0.03s
Training model RNN Depth 3
Evaluated RNN Depth 3 in 0.04s

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [36]:
display(score_df.sort_values(by="f1-score", ascending=False))

                             model  accuracy  precision    recall  f1-score
14                NN Depth 2 (BOW)  0.727697   0.885284  0.799566  0.837566
15             NN Depth 3 (TF-IDF)  0.744856   0.872350  0.808034  0.835309
16                NN Depth 3 (BOW)  0.701112   0.859137  0.806271  0.829920
4              Decision Tree (BOW)  0.655771   0.848781  0.800572  0.822721
13             NN Depth 2 (TF-IDF)  0.762078   0.926705  0.746710  0.813017
3           Decision Tree (TF-IDF)  0.626534   0.823943  0.791150  0.806205
2                     Linear (BOW)  0.698620   0.912369  0.714989  0.798001
1                  Linear (TF-IDF)  0.736580   0.952171  0.646942  0.739849
12                NN Depth 1 (BOW)  0.723958   0.949070  0.624361  0.722881
18  Decision Tree (Distilled BERT)  0.390000   0.677843  0.718462  0.696433
0                 Random Predictor  0.236340   0.584595  0.858719  0.685429
6                RNN Depth 1 (BOW)  0.525882   0.682369  0.510036  0.508252
8                RNN Depth 2 (BOW)  0.590123   0.669825  0.464819  0.457066
11             NN Depth 1 (TF-IDF)  0.606020   0.666904  0.412344  0.448852
19     NN Depth 1 (Distilled BERT)  0.002000   0.308354  0.614194  0.399367
21     NN Depth 3 (Distilled BERT)  0.000000   0.284565  0.617135  0.389500
20     NN Depth 2 (Distilled BERT)  0.000000   0.205079  0.438202  0.279399
5             RNN Depth 1 (TF-IDF)  0.056173   0.435816  0.412403  0.259336
10               RNN Depth 3 (BOW)  0.465219   0.536295  0.064753  0.108833
9             RNN Depth 3 (TF-IDF)  0.453381   0.315010  0.031790  0.057752
7             RNN Depth 2 (TF-IDF)  0.436094   0.062131  0.013463  0.022131
17         Linear (Distilled BERT)  0.460000   0.000000  0.000000  0.000000
22    RNN Depth 1 (Distilled BERT)  0.460000   0.000000  0.000000  0.000000
23    RNN Depth 2 (Distilled BERT)  0.460000   0.000000  0.000000  0.000000
24    RNN Depth 3 (Distilled BERT)  0.460000   0.000000  0.000000  0.000000

### Word2Vec

In [64]:
# Word2Vec

# moved the import here to avoid OOM for BERT
!pip install gensim
from gensim.models import Word2Vec
# Note, I failed to get GloVe working, so I will skip it for now
# BERT should outperform both Word2Vec and GloVe in theory

class Word2Vec_encoder:
    def __init__(self, vector_size=1000):
        self.vector_size = vector_size
        self.model = None

    def fit(self, texts):
        tokenized = [text.split() for text in texts]
        self.model = Word2Vec(sentences=tokenized, vector_size=self.vector_size, window=5, min_count=1, workers=4)

    def transform(self, texts):
        tokenized = [text.split() for text in texts]
        embeddings = []
        for tokens in tokenized:
            token_vecs = []
            for token in tokens:
                if token in self.model.wv:
                    token_vecs.append(self.model.wv[token])
            if token_vecs:
                embeddings.append(np.mean(token_vecs, axis=0))
            else:
                embeddings.append(np.zeros(self.vector_size))
        
        # Use vstack to properly handle array creation
        if embeddings:
            return np.vstack(embeddings)
        else:
            return np.array([]).reshape(0, self.vector_size)
    
word2vec_encoder = Word2Vec_encoder(vector_size=1000)
word2vec_encoder.fit(train_df["text"].tolist())

Requirement already satisfied: gensim in /usr/local/lib/python3.12/dist-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.2.1)

In [38]:
display(score_df.sort_values(by="f1-score", ascending=False))
# Word2Vec performs much worse than TF-IDF and BOW, 
# likely because the dataset is small and Word2Vec doesn't have enough data to learn good word embeddings, while TF-IDF and BOW can still extract useful features based on word frequency.
# this may indicate context sensitive embedding is not very useful for this dataset, and simple frequency based features are more effective
# We continue with gpt2 anyway to verify this hypothesis

                             model  accuracy  precision    recall  f1-score
14                NN Depth 2 (BOW)  0.727697   0.885284  0.799566  0.837566
15             NN Depth 3 (TF-IDF)  0.744856   0.872350  0.808034  0.835309
16                NN Depth 3 (BOW)  0.701112   0.859137  0.806271  0.829920
4              Decision Tree (BOW)  0.655771   0.848781  0.800572  0.822721
13             NN Depth 2 (TF-IDF)  0.762078   0.926705  0.746710  0.813017
3           Decision Tree (TF-IDF)  0.626534   0.823943  0.791150  0.806205
2                     Linear (BOW)  0.698620   0.912369  0.714989  0.798001
1                  Linear (TF-IDF)  0.736580   0.952171  0.646942  0.739849
12                NN Depth 1 (BOW)  0.723958   0.949070  0.624361  0.722881
18  Decision Tree (Distilled BERT)  0.390000   0.677843  0.718462  0.696433
0                 Random Predictor  0.236340   0.584595  0.858719  0.685429
6                RNN Depth 1 (BOW)  0.525882   0.682369  0.510036  0.508252
8                RNN Depth 2 (BOW)  0.590123   0.669825  0.464819  0.457066
11             NN Depth 1 (TF-IDF)  0.606020   0.666904  0.412344  0.448852
19     NN Depth 1 (Distilled BERT)  0.002000   0.308354  0.614194  0.399367
21     NN Depth 3 (Distilled BERT)  0.000000   0.284565  0.617135  0.389500
20     NN Depth 2 (Distilled BERT)  0.000000   0.205079  0.438202  0.279399
5             RNN Depth 1 (TF-IDF)  0.056173   0.435816  0.412403  0.259336
10               RNN Depth 3 (BOW)  0.465219   0.536295  0.064753  0.108833
9             RNN Depth 3 (TF-IDF)  0.453381   0.315010  0.031790  0.057752
7             RNN Depth 2 (TF-IDF)  0.436094   0.062131  0.013463  0.022131
17         Linear (Distilled BERT)  0.460000   0.000000  0.000000  0.000000
22    RNN Depth 1 (Distilled BERT)  0.460000   0.000000  0.000000  0.000000
23    RNN Depth 2 (Distilled BERT)  0.460000   0.000000  0.000000  0.000000
24    RNN Depth 3 (Distilled BERT)  0.460000   0.000000  0.000000  0.000000

## LLM as encoders

In [39]:
# GPT2
from transformers import GPT2Tokenizer, GPT2Model

tokenizer_gpt2 = GPT2Tokenizer.from_pretrained("gpt2")
model_gpt2 = GPT2Model.from_pretrained("gpt2")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

In [40]:
# test
start_time = time.time()


text = "This is a test sentence for GPT-2 encoding."
class_inputs = tokenizer_gpt2(text, return_tensors="pt")
logits = model_gpt2(**class_inputs).last_hidden_state.mean(dim=1).detach().numpy()

print("GPT-2 encoding shape:", logits.shape)
end_time = time.time()

print(f"GPT-2 encoding time: {end_time - start_time:.2f}s")

GPT-2 encoding shape: (1, 768)
GPT-2 encoding time: 0.11s

In [41]:
# test batch encoding
tokenizer_gpt2.pad_token = tokenizer_gpt2.eos_token # set pad token to eos token
def single_batch_encoding(texts, i, batch_size=32, max_length=512):
    batch_texts = texts[i:i+batch_size]
    inputs = tokenizer_gpt2(batch_texts, return_tensors="pt", padding=True, truncation=True, max_length=max_length)
    with torch.no_grad():
        logits = model_gpt2(**inputs).last_hidden_state.mean(dim=1).numpy()
    return logits

In [42]:
for bs in [8, 16, 32, 64]:
    start_time = time.time()
    batch_logits = single_batch_encoding(train_df["text"].tolist(), 0, batch_size=bs, max_length=50)
    end_time = time.time()
    print(f"GPT-2 encoding time with batch size {bs}: {end_time - start_time:.2f}s, expected {(end_time - start_time) * (len(train_df) / bs):.2f}s for full dataset")

GPT-2 encoding time with batch size 8: 0.76s, expected 661.82s for full dataset
GPT-2 encoding time with batch size 16: 1.51s, expected 656.09s for full dataset
GPT-2 encoding time with batch size 32: 2.87s, expected 623.81s for full dataset
GPT-2 encoding time with batch size 64: 7.94s, expected 862.70s for full dataset

In [44]:
# GPT-2 is faster than BERT distilled somehow

FORCED_TRAIN_SIZE = 100 # train on all available training samples to ensure sufficient class diversity
BATCH_SIZE = 16

new_train_indices = np.random.choice(train_df.index, size=FORCED_TRAIN_SIZE, replace=False)
gpt2_train_df = train_df.loc[new_train_indices].reset_index(drop=True)

new_test_indices = np.random.choice(test_df.index, size=FORCED_TRAIN_SIZE * 10, replace=False)
gpt2_test_df = test_df.loc[new_test_indices].reset_index(drop=True)

# encode the full train and test sets
encoded_train_gpt2 = []
for i in range(0, FORCED_TRAIN_SIZE, BATCH_SIZE):
    batch_logits = single_batch_encoding(gpt2_train_df["text"].tolist(), i, batch_size=BATCH_SIZE, max_length=50)
    encoded_train_gpt2.append(batch_logits)
    # print progress
    progress = min(i + BATCH_SIZE, FORCED_TRAIN_SIZE) / FORCED_TRAIN_SIZE * 100
    print(f"Encoded {min(i + BATCH_SIZE, FORCED_TRAIN_SIZE)} / {FORCED_TRAIN_SIZE} ({progress:.2f}%)", end="\r")

print()
FORCED_TEST_SIZE = FORCED_TRAIN_SIZE * 10 # encode 1120 samples for testing
encoded_test_gpt2 = []
for i in range(0, FORCED_TEST_SIZE, BATCH_SIZE):
    batch_logits = single_batch_encoding(gpt2_test_df["text"].tolist(), i, batch_size=BATCH_SIZE, max_length=50)
    encoded_test_gpt2.append(batch_logits)
    # print progress
    progress = min(i + BATCH_SIZE, FORCED_TEST_SIZE) / FORCED_TEST_SIZE * 100
    print(f"Encoded {min(i + BATCH_SIZE, FORCED_TEST_SIZE)} / {FORCED_TEST_SIZE} ({progress:.2f}%)", end="\r")

print()

Encoded 100 / 100 (100.00%)
Encoded 1000 / 1000 (100.00%)

In [45]:
# linear failed to converged, we do some scaling
linear_scaling_factor = 10
model_linear_scaled = MultiOutputClassifier(LogisticRegression(max_iter=5000, C=linear_scaling_factor))

EMBED_DIM = 768 # GPT-2 base hidden size
nn_depth1 = make_nn_model(depth=1, in_dim=EMBED_DIM, epochs=10, lr=1e-4)
nn_depth2 = make_nn_model(depth=2, in_dim=EMBED_DIM, epochs=10, lr=1e-4)
nn_depth3 = make_nn_model(depth=3, in_dim=EMBED_DIM, epochs=10, lr=1e-4)

rnn_bert1 = make_rnn_model(depth=1, in_dim=EMBED_DIM, epochs=10, lr=1e-4)
rnn_bert2 = make_rnn_model(depth=2, in_dim=EMBED_DIM, epochs=10, lr=1e-4)
rnn_bert3 = make_rnn_model(depth=3, in_dim=EMBED_DIM, epochs=10, lr=1e-4)

train_and_test(
    models=[
        ("Linear", model_linear_scaled),
        ("Decision Tree", model_decision_tree),
        ("NN Depth 1", nn_depth1),
        ("NN Depth 2", nn_depth2),
        ("NN Depth 3", nn_depth3),
        ("RNN Depth 1", rnn_bert1),
        ("RNN Depth 2", rnn_bert2),
        ("RNN Depth 3", rnn_bert3),
    ],
    encoders=[
        ("GPT-2", None), # pass None since we are pre-encoding the data, and predictor will use the pre-encoded data directly
    ],
    quiet=True,
    X_train_encoded={"GPT-2": np.vstack(encoded_train_gpt2)}, # pass pre-encoded data to skip encoding again
    X_test_encoded={"GPT-2": np.vstack(encoded_test_gpt2)}, # pass pre-encoded data to skip encoding again
    forced_train_df = gpt2_train_df, # use the new smaller train set
    forced_test_df = gpt2_test_df, # use the new smaller test set
)

Depth 1 Layer 0: 768 -> 7
Depth 2 Layer 0: 768 -> 128
Depth 2 Layer 1: 128 -> 7
Depth 3 Layer 0: 768 -> 128
Depth 3 Layer 1: 128 -> 64
Depth 3 Layer 2: 64 -> 7
Training model Linear
Evaluated Linear in 3.23s
Training model Decision Tree
Evaluated Decision Tree in 0.24s
Training model NN Depth 1
Evaluated NN Depth 1 in 0.06s
Training model NN Depth 2
Evaluated NN Depth 2 in 0.09s
Training model NN Depth 3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Evaluated NN Depth 3 in 0.10s
Training model RNN Depth 1
Evaluated RNN Depth 1 in 0.05s
Training model RNN Depth 2
Evaluated RNN Depth 2 in 0.05s
Training model RNN Depth 3
Evaluated RNN Depth 3 in 0.06s

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

## Embedding models as zero shot predictors

In [59]:
Prompts = [
    # class 1, isSuspicious
    ("This is a normal tweet.",            
     "This tweet contains harmful content and should be flagged, can contain contents that are racist, sexist, hateful, or suicidal."),
    # class 2, isRacist
    ("This is a normal tweet.",
     "This tweet contains racist content and should be flagged, can contain discriminatory or derogatory language targeting specific races like asian, black, etc."),
    # class 3, isSexist
    ("This is a normal tweet.",
     "This tweet contains sexist content and should be flagged, can contain discriminatory or derogatory language targeting man or women."),
    # class 4, isHate
    ("This is a normal tweet.",
     "This tweet contains hateful content and should be flagged, can contain language that promotes violence or hatred against individuals or groups based on attributes like race, religion, gender, beliefs, etc."),
    # class 5, isDepressive
    ("This is a normal tweet.",
     "This tweet contains depressive content and should be flagged, can contain language that expresses feelings of sadness, hopelessness, or worthlessness."),
    # class 6, isSuicidal
    ("This is a normal tweet.",
     "This tweet contains suicidal content and should be flagged, can contain language that expresses thoughts of self-harm or the desire to end one's own life."),
    # class 7, isAnxiety
    ("This is a normal tweet.",
     "This tweet contains anxiety content and should be flagged, can contain language that expresses excessive worry, fear, or nervousness."),
]

class ZeroShotModel:
    def __init__(self, tokenizer, model):
        self.tokenizer = tokenizer
        self.model = model
        self.prompt_embeddings = []
        for normal_prompt, class_prompt in Prompts:
            if self.tokenizer is not None:
                class_inputs = self.tokenizer(class_prompt, return_tensors="pt", truncation=True, max_length=50)
                normal_inputs = self.tokenizer(normal_prompt, return_tensors="pt", truncation=True, max_length=50)
            else:
                class_inputs = class_prompt
                normal_inputs = normal_prompt
            
            with torch.no_grad():
                if self.tokenizer is not None:
                    CR = self.model(**class_inputs)
                    NR = self.model(**normal_inputs)

                    if "last_hidden_state" in CR and "last_hidden_state" in NR:
                        class_embedding = CR.last_hidden_state.mean(dim=1).squeeze().numpy()
                        normal_embedding = NR.last_hidden_state.mean(dim=1).squeeze().numpy()
                    elif "logits" in CR and "logits" in NR:
                        class_embedding = CR.logits.mean(dim=1).squeeze().numpy()
                        normal_embedding = NR.logits.mean(dim=1).squeeze().numpy()
                    else:
                        print("CR keys:", CR.keys())
                        raise ValueError("Unsupported model output format for zero-shot embedding extraction")
                else:
                    class_embedding = self.model.transform([class_prompt])[0]
                    normal_embedding = self.model.transform([normal_prompt])[0]
            
            self.prompt_embeddings.append((normal_embedding, class_embedding))
        
    def fit(self, X, Y):
        return # no fitting needed for zero-shot

    def predict(self, X):
        if sp.issparse(X):
            X = X.toarray()
        X = np.asarray(X)
        # X is an encoded text embedding, we will compare it with the prompt embeddings using cosine similarity
        predictions = []
        for x in X:
            sample_preds = []
            for normal_emb, class_emb in self.prompt_embeddings:
                sim_normal = np.dot(x, normal_emb) / (np.linalg.norm(x) * np.linalg.norm(normal_emb) + 1e-8)
                sim_class  = np.dot(x, class_emb) / (np.linalg.norm(x) * np.linalg.norm(class_emb) + 1e-8)
                # if the embedding is closer to the class prompt than the normal prompt, we predict 1, else 0
                sim_score_class = np.sum(sim_class)
                sim_score_normal = np.sum(sim_normal)
                pred = 1 if sim_score_class > sim_score_normal else 0
                sample_preds.append(pred)
            predictions.append(sample_preds)
        return np.array(predictions)

In [60]:
train_and_test(
    models=[
        ("Zero-Shot GPT-2", ZeroShotModel(tokenizer_gpt2, model_gpt2)),
    ],
    encoders=[
        ("GPT-2", None), # pass None since we are pre-encoding the data, and predictor will use the pre-encoded data directly
    ],
    quiet=True,
    X_train_encoded={"GPT-2": np.vstack(encoded_train_gpt2)}, # pass pre-encoded data to skip encoding again
    X_test_encoded={"GPT-2": np.vstack(encoded_test_gpt2)}, # pass pre-encoded data to skip encoding again
    forced_train_df = bert_train_df, # use the new smaller train set
    forced_test_df = bert_test_df, # use the new smaller test set
)

Training model Zero-Shot GPT-2
Evaluated Zero-Shot GPT-2 in 0.21s

In [65]:
train_and_test(
    models=[
        ("Zero-Shot Word2Vec", ZeroShotModel(None, word2vec_encoder)), # word2vec dont need tokenization
    ],
    encoders=[
        ("Word2Vec", word2vec_encoder),
    ],
    quiet=True,
)

Encoded X_train with 1 encoders in 1.07s, averaged 1.07s / encoder
Training model Zero-Shot Word2Vec
Evaluated Zero-Shot Word2Vec in 25.83s

In [62]:
train_and_test(
    models=[
        ("Zero-Shot BERT", ZeroShotModel(bert_tokenizer, bert_model)),
    ],
    encoders=[
        ("BERT", None), # pass None since we are pre-encoding the data, and predictor will use the pre-encoded data directly
    ],
    quiet=True,
    X_train_encoded={"BERT": bert_train_encodings}, # pass pre-encoded data to skip encoding again
    X_test_encoded={"BERT": bert_test_encodings}, # pass pre-encoded data to skip encoding again
    forced_test_df=bert_test_df, # use the new smaller test set
    forced_train_df=bert_train_df, # use the new smaller train set
)

Training model Zero-Shot BERT
Evaluated Zero-Shot BERT in 0.08s

In [67]:
# remove duplicated model (if any)
score_df = score_df.drop_duplicates(subset=["model"])
display(score_df.sort_values(by="f1-score", ascending=False))

                             model  accuracy  precision    recall  f1-score
14                NN Depth 2 (BOW)  0.727697   0.885284  0.799566  0.837566
15             NN Depth 3 (TF-IDF)  0.744856   0.872350  0.808034  0.835309
16                NN Depth 3 (BOW)  0.701112   0.859137  0.806271  0.829920
4              Decision Tree (BOW)  0.655771   0.848781  0.800572  0.822721
13             NN Depth 2 (TF-IDF)  0.762078   0.926705  0.746710  0.813017
3           Decision Tree (TF-IDF)  0.626534   0.823943  0.791150  0.806205
2                     Linear (BOW)  0.698620   0.912369  0.714989  0.798001
36   Zero-Shot Word2Vec (Word2Vec)  0.530275   0.634212  0.974199  0.763893
1                  Linear (TF-IDF)  0.736580   0.952171  0.646942  0.739849
12                NN Depth 1 (BOW)  0.723958   0.949070  0.624361  0.722881
26           Decision Tree (GPT-2)  0.464000   0.783269  0.643478  0.702702
18  Decision Tree (Distilled BERT)  0.390000   0.677843  0.718462  0.696433
0                 Random Predictor  0.236340   0.584595  0.858719  0.685429
33         Zero-Shot GPT-2 (GPT-2)  0.378000   0.615427  0.773288  0.681465
27              NN Depth 1 (GPT-2)  0.207000   0.575636  0.852717  0.678464
25                  Linear (GPT-2)  0.550000   0.830086  0.553623  0.661861
30             RNN Depth 1 (GPT-2)  0.280000   0.649240  0.592780  0.544794
6                RNN Depth 1 (BOW)  0.525882   0.682369  0.510036  0.508252
35           Zero-Shot BERT (BERT)  0.308000   0.537670  0.468809  0.463162
8                RNN Depth 2 (BOW)  0.590123   0.669825  0.464819  0.457066
11             NN Depth 1 (TF-IDF)  0.606020   0.666904  0.412344  0.448852
19     NN Depth 1 (Distilled BERT)  0.002000   0.308354  0.614194  0.399367
21     NN Depth 3 (Distilled BERT)  0.000000   0.284565  0.617135  0.389500
31             RNN Depth 2 (GPT-2)  0.329000   0.308658  0.509684  0.384121
20     NN Depth 2 (Distilled BERT)  0.000000   0.205079  0.438202  0.279399
5             RNN Depth 1 (TF-IDF)  0.056173   0.435816  0.412403  0.259336
28              NN Depth 2 (GPT-2)  0.413000   0.227801  0.143596  0.174683
10               RNN Depth 3 (BOW)  0.465219   0.536295  0.064753  0.108833
9             RNN Depth 3 (TF-IDF)  0.453381   0.315010  0.031790  0.057752
7             RNN Depth 2 (TF-IDF)  0.436094   0.062131  0.013463  0.022131
17         Linear (Distilled BERT)  0.460000   0.000000  0.000000  0.000000
22    RNN Depth 1 (Distilled BERT)  0.460000   0.000000  0.000000  0.000000
24    RNN Depth 3 (Distilled BERT)  0.460000   0.000000  0.000000  0.000000
23    RNN Depth 2 (Distilled BERT)  0.460000   0.000000  0.000000  0.000000
29              NN Depth 3 (GPT-2)  0.412000   0.000000  0.000000  0.000000
32             RNN Depth 3 (GPT-2)  0.412000   0.000000  0.000000  0.000000